# Generated by Django 6.0.6 on 2026-07-11 11:44

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0014_alter_dsrs_attachments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Source_Type", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=50)),
                ("status_date", models.DateField()),
                ("facility", models.CharField(blank=True, max_length=200, null=True)),
                ("contract_signed", models.BooleanField(default=False)),
                ("contract_signed_date", models.DateField(blank=True, null=True)),
                ("payment_done", models.BooleanField(default=False)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("licence_valid", models.BooleanField(default=False)),
                ("licence_issue_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dsrs",
                    models.ManyToManyField(
                        related_name="contracts", to="dashboard.dsrs"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalContract",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("Source_Type", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=50)),
                ("status_date", models.DateField()),
                ("facility", models.CharField(blank=True, max_length=200, null=True)),
                ("contract_signed", models.BooleanField(default=False)),
                ("contract_signed_date", models.DateField(blank=True, null=True)),
                ("payment_done", models.BooleanField(default=False)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("licence_valid", models.BooleanField(default=False)),
                ("licence_issue_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical contract",
                "verbose_name_plural": "historical contracts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
