# Generated by Django 6.0.6 on 2026-07-26 08:10

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Source_Type", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=50)),
                ("status_date", models.DateField()),
                ("contract_signed", models.BooleanField(default=False)),
                ("contract_signed_date", models.DateField(blank=True, null=True)),
                ("payment_done", models.BooleanField(default=False)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("licence_valid", models.BooleanField(default=False)),
                ("licence_issue_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalContract",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("Source_Type", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=50)),
                ("status_date", models.DateField()),
                ("contract_signed", models.BooleanField(default=False)),
                ("contract_signed_date", models.DateField(blank=True, null=True)),
                ("payment_done", models.BooleanField(default=False)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("licence_valid", models.BooleanField(default=False)),
                ("licence_issue_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical contract",
                "verbose_name_plural": "historical contracts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LicenseContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("contract_date", models.DateField(blank=True, null=True)),
                (
                    "contract_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("draft_sent_to_customer", models.BooleanField(default=False)),
                ("draft_sent_date", models.DateField(blank=True, null=True)),
                (
                    "notification_letter_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("notification_letter_date", models.DateField(blank=True, null=True)),
                ("amendment_notes", models.TextField(blank=True, null=True)),
                (
                    "source_owner",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contract_accountable",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
