# Generated by Django 6.0.5 on 2026-06-02 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("status_date", models.DateField()),
                ("transferred_facility", models.CharField(max_length=200)),
                ("serial_number", models.CharField(max_length=100)),
                ("nuclide", models.CharField(max_length=100)),
                ("activity", models.FloatField(blank=True, null=True)),
                (
                    "activity_unit",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("activity_date", models.DateField(blank=True, null=True)),
                ("payment_done", models.BooleanField(default=False)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("contract_signed", models.BooleanField(default=False)),
                ("contract_signed_date", models.DateField(blank=True, null=True)),
                ("licence_valid", models.BooleanField(default=False)),
                ("licence_issue_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dsrs",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="dashboard.dsrs"
                    ),
                ),
            ],
        ),
    ]
