# Generated by Django 6.0.5 on 2026-06-07 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0001_initial"),
        ("dashboard", "0006_remove_dsrs_transfer_facility_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="dsrs",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="dashboard.dsrs",
            ),
        ),
    ]
