# Generated by Django 6.0.6 on 2026-07-26 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contract", "0001_initial"),
        ("dashboard", "0001_initial"),
        ("facilities", "0001_initial"),
        ("operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="dsrs",
            field=models.ManyToManyField(related_name="contracts", to="dashboard.dsrs"),
        ),
        migrations.AddField(
            model_name="contract",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sources",
                to="facilities.facilitymodel",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="facilities.facilitymodel",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="licensecontract",
            name="license",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contract",
                to="operations.licenserequest",
            ),
        ),
    ]
