# Generated by Django 6.0.6 on 2026-07-22 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0001_initial"),
        ("operations", "0010_remove_licenserequest_contract_cost_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("contract_date", models.DateField(blank=True, null=True)),
                (
                    "contract_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("draft_sent_to_customer", models.BooleanField(default=False)),
                ("draft_sent_date", models.DateField(blank=True, null=True)),
                (
                    "notification_letter_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notification_letter_date", models.DateField(blank=True, null=True)),
                ("amendment_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract_accountable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accountable_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "license",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract",
                        to="operations.licenserequest",
                    ),
                ),
                (
                    "source_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_owner_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
