# Generated by Django 6.0.5 on 2026-06-07 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0002_alter_contract_dsrs"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="transferred_facility",
            new_name="facility",
        ),
    ]
