# Generated by Django 6.0.6 on 2026-07-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="licensecontract",
            name="send_to_financial",
            field=models.BooleanField(default=False),
        ),
    ]
