# Generated by Django 6.0.6 on 2026-07-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0002_licensecontract"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licensecontract",
            name="contract_accountable",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="licensecontract",
            name="source_owner",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
