# Generated by Django 6.0.5 on 2026-06-07 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0003_rename_transferred_facility_contract_facility"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_number", models.CharField()),
                ("facility", models.CharField(max_length=200)),
                ("contract_signed", models.BooleanField(default=False)),
                ("contract_signed_date", models.DateField(blank=True, null=True)),
                ("payment_done", models.BooleanField(default=False)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("licence_valid", models.BooleanField(default=False)),
                ("licence_issue_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="contract",
            name="contract_signed",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="contract_signed_date",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="facility",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="licence_issue_date",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="licence_valid",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="payment_date",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="payment_done",
        ),
        migrations.AddField(
            model_name="contract",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contract.contractgroup",
            ),
        ),
    ]
