# Generated by Django 6.0.6 on 2026-07-29 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0003_licensecontract_send_to_financial"),
        ("dashboard", "0006_alter_dsrs_location_alter_historicaldsrs_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="Source_Type",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="contract_signed",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="contract_signed_date",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="facility",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="licence_issue_date",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="licence_valid",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="status",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="status_date",
        ),
        migrations.RemoveField(
            model_name="historicalcontract",
            name="Source_Type",
        ),
        migrations.RemoveField(
            model_name="historicalcontract",
            name="contract_signed",
        ),
        migrations.RemoveField(
            model_name="historicalcontract",
            name="contract_signed_date",
        ),
        migrations.RemoveField(
            model_name="historicalcontract",
            name="facility",
        ),
        migrations.RemoveField(
            model_name="historicalcontract",
            name="licence_issue_date",
        ),
        migrations.RemoveField(
            model_name="historicalcontract",
            name="licence_valid",
        ),
        migrations.RemoveField(
            model_name="historicalcontract",
            name="status",
        ),
        migrations.RemoveField(
            model_name="historicalcontract",
            name="status_date",
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="dsrs",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dashboard.dsrs",
            ),
        ),
        migrations.RemoveField(
            model_name="contract",
            name="dsrs",
        ),
        migrations.AddField(
            model_name="contract",
            name="dsrs",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pi_record",
                to="dashboard.dsrs",
            ),
        ),
    ]
