# Generated by Django 6.0.6 on 2026-07-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0003_alter_licensecontract_contract_accountable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licensecontract",
            name="contract_accountable",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="licensecontract",
            name="notification_letter_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="licensecontract",
            name="source_owner",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
