# Generated by Django 6.0.5 on 2026-06-07 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0004_contractgroup_remove_contract_contract_signed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="group",
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_signed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="facility",
            field=models.CharField(
                default=datetime.datetime(
                    2026, 6, 7, 12, 12, 15, 956667, tzinfo=datetime.timezone.utc
                ),
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="licence_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="licence_valid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contract",
            name="payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="payment_done",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="ContractGroup",
        ),
    ]
