# Generated by Django 6.0.6 on 2026-08-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0004_remove_contract_source_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="payment_date",
            field=models.DateField(blank=True, null=True, verbose_name="Payment Date"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="payment_done",
            field=models.BooleanField(default=False, verbose_name="Payment Done"),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="payment_date",
            field=models.DateField(blank=True, null=True, verbose_name="Payment Date"),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="payment_done",
            field=models.BooleanField(default=False, verbose_name="Payment Done"),
        ),
        migrations.AlterField(
            model_name="licensecontract",
            name="amendment_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Amendment Notes"
            ),
        ),
        migrations.AlterField(
            model_name="licensecontract",
            name="contract_accountable",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Contract Accountable",
            ),
        ),
        migrations.AlterField(
            model_name="licensecontract",
            name="contract_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Contract Cost",
            ),
        ),
        migrations.AlterField(
            model_name="licensecontract",
            name="contract_date",
            field=models.DateField(blank=True, null=True, verbose_name="Contract Date"),
        ),
        migrations.AlterField(
            model_name="licensecontract",
            name="contract_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Contract Number"
            ),
        ),
        migrations.AlterField(
            model_name="licensecontract",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="licensecontract",
            name="draft_sent_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Draft Sent Date"
            ),
        ),
        migrations.AlterField(
            model_name="licensecontract",
            name="draft_sent_to_customer",
            field=models.BooleanField(
                default=False, verbose_name="Draft Sent to Customer"
            ),
        ),
        migrations.AlterField(
            model_name="licensecontract",
            name="notification_letter_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Notification Letter Date"
            ),
        ),
        migrations.AlterField(
            model_name="licensecontract",
            name="notification_letter_number",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Notification Letter Number",
            ),
        ),
        migrations.AlterField(
            model_name="licensecontract",
            name="send_to_financial",
            field=models.BooleanField(default=False, verbose_name="Send to Financial"),
        ),
        migrations.AlterField(
            model_name="licensecontract",
            name="source_owner",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Source Owner"
            ),
        ),
        migrations.AlterField(
            model_name="licensecontract",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
