# Generated by Django 6.0.5 on 2026-06-09 09:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0005_remove_contract_group_contract_contract_signed_and_more"),
        ("dashboard", "0010_remove_dsrs_create_contract_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalContract",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("status_date", models.DateField()),
                ("facility", models.CharField(max_length=200)),
                ("serial_number", models.CharField(max_length=100)),
                ("nuclide", models.CharField(max_length=100)),
                ("activity", models.FloatField(blank=True, null=True)),
                (
                    "activity_unit",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("activity_date", models.DateField(blank=True, null=True)),
                ("contract_signed", models.BooleanField(default=False)),
                ("contract_signed_date", models.DateField(blank=True, null=True)),
                ("payment_done", models.BooleanField(default=False)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("licence_valid", models.BooleanField(default=False)),
                ("licence_issue_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "dsrs",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dashboard.dsrs",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical contract",
                "verbose_name_plural": "historical contracts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
