# Generated by Django 6.0.6 on 2026-08-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0005_alter_contract_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="licensecontract",
            name="draft_letter_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Draft Letter Date"
            ),
        ),
        migrations.AddField(
            model_name="licensecontract",
            name="draft_letter_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Draft Letter Number"
            ),
        ),
    ]
