# Generated by Django 6.0.5 on 2026-06-10 10:11

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0006_historicalcontract"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="Source_Type",
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="Source_Type",
            field=models.CharField(
                default=datetime.datetime(
                    2026, 6, 10, 10, 11, 7, 96255, tzinfo=datetime.timezone.utc
                ),
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
