# Generated by Django 6.0.6 on 2026-08-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0006_licensecontract_draft_letter_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="licensecontract",
            name="License_letter_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="License Letter Date"
            ),
        ),
        migrations.AddField(
            model_name="licensecontract",
            name="License_letter_number",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="License Letter Number",
            ),
        ),
    ]
