# Generated by Django 6.0.6 on 2026-08-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0007_licensecontract_license_letter_date_and_more"),
        ("dashboard", "0008_alter_dsrs_options_alter_hideshowfiltert_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalcontract",
            name="dsrs",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="dsrs",
        ),
        migrations.AddField(
            model_name="contract",
            name="dsrs",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="pi_record", to="dashboard.dsrs"
            ),
        ),
    ]
