# Generated by Django 6.0.6 on 2026-09-12 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0008_alter_dsrs_options_alter_hideshowfiltert_options_and_more'),
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_form', models.ImageField(help_text='Scanned copy of the signed paper request, JPEG.', upload_to='sell_source/request_forms/', verbose_name='DSRS Sale Request Form (scanned)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft — Request Form Uploaded'), ('SPECIFICATION', 'Adding Sources'), ('WAITING_CEO', 'Waiting CEO Signature'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('status_date', models.DateTimeField(blank=True, null=True, verbose_name='Status Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('ceo_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('ceo_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Approved By (CEO)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sell_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Sell Source Request',
                'verbose_name_plural': 'Sell Source Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellRequestSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='شماره سریال / Serial Number')),
                ('manufacture_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ساخت / Manufacture Date')),
                ('recorded_activity_mci', models.FloatField(blank=True, null=True, verbose_name='پرتوزایی ثبت\u200cشده / Recorded Activity (mCi)')),
                ('physical_characteristics', models.TextField(blank=True, verbose_name='مشخصات فیزیکی / Physical Characteristics')),
                ('remarks', models.TextField(blank=True, verbose_name='ملاحظات / Remarks')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('dsrs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sell_request_sources', to='dashboard.dsrs', verbose_name='Source (DSRS)')),
                ('nuclide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.nuclides', verbose_name='نام ماده پرتوزا / Nuclide')),
                ('sell_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='sell_source.sellrequest', verbose_name='Sell Request')),
            ],
            options={
                'verbose_name': 'Sell Request Source',
                'verbose_name_plural': 'Sell Request Sources',
                'ordering': ['id'],
            },
        ),
    ]
