# Generated by Django 6.0.6 on 2026-09-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellrequest',
            name='filled_form',
            field=models.ImageField(blank=True, null=True, upload_to='sell_source/filled_forms/', verbose_name='Filled Form'),
        ),
    ]
