# Generated by Django 6.0.6 on 2026-09-13 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0001_initial"),
        ("sell_source", "0002_sellrequest_filled_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellrequestsource",
            name="manufacture_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Manufacture Date"
            ),
        ),
        migrations.AlterField(
            model_name="sellrequestsource",
            name="nuclide",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="reference.nuclides",
                verbose_name="Nuclide",
            ),
        ),
        migrations.AlterField(
            model_name="sellrequestsource",
            name="physical_characteristics",
            field=models.TextField(blank=True, verbose_name="Physical Characteristics"),
        ),
        migrations.AlterField(
            model_name="sellrequestsource",
            name="recorded_activity_mci",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Recorded Activity (mCi)"
            ),
        ),
        migrations.AlterField(
            model_name="sellrequestsource",
            name="remarks",
            field=models.TextField(blank=True, verbose_name="Remarks"),
        ),
        migrations.AlterField(
            model_name="sellrequestsource",
            name="serial_number",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="  Serial Number"
            ),
        ),
    ]
