# Generated by Django 6.0.5 on 2026-06-10 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("model_name", models.CharField(max_length=100)),
                ("x_field", models.CharField(max_length=100)),
                ("y_field", models.CharField(max_length=100)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("bar", "Bar"),
                            ("line", "Line"),
                            ("pie", "Pie"),
                            ("scatter", "Scatter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
                ("width", models.IntegerField(default=6)),
                ("height", models.IntegerField(default=4)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to="analytics.dashboard",
                    ),
                ),
            ],
        ),
    ]
