# Generated by Django 6.0.5 on 2026-06-10 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboard",
            name="owner",
        ),
        migrations.CreateModel(
            name="DashboardC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("global_filters", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("model_name", models.CharField(max_length=100)),
                ("x_field", models.CharField(max_length=100)),
                ("y_field", models.CharField(max_length=100)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("bar", "Bar"),
                            ("line", "Line"),
                            ("pie", "Pie"),
                            ("scatter", "Scatter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("x", models.IntegerField(default=0)),
                ("y", models.IntegerField(default=0)),
                ("w", models.IntegerField(default=4)),
                ("h", models.IntegerField(default=3)),
                ("refresh_interval", models.IntegerField(default=0)),
                (
                    "dashboardC",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="analytics.dashboardc",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Chart",
        ),
        migrations.DeleteModel(
            name="Dashboard",
        ),
    ]
