# Generated by Django 6.0.5 on 2026-06-10 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_remove_dashboard_owner_dashboardc_widget_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="widget",
            name="dashboardC",
        ),
        migrations.CreateModel(
            name="AnalyticsPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("global_filters", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnalyticsWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("model_name", models.CharField(max_length=100)),
                ("x_field", models.CharField(max_length=100)),
                ("y_field", models.CharField(blank=True, max_length=100)),
                (
                    "aggregation",
                    models.CharField(
                        choices=[
                            ("sum", "Sum"),
                            ("count", "Count"),
                            ("avg", "Average"),
                            ("min", "Minimum"),
                            ("max", "Maximum"),
                        ],
                        default="count",
                        max_length=20,
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("bar", "Bar"),
                            ("line", "Line"),
                            ("pie", "Pie"),
                            ("scatter", "Scatter"),
                            ("doughnut", "Doughnut"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("x", models.IntegerField(default=0)),
                ("y", models.IntegerField(default=0)),
                ("width", models.IntegerField(default=6)),
                ("height", models.IntegerField(default=4)),
                (
                    "refresh_interval",
                    models.IntegerField(
                        default=0, help_text="Seconds. 0 = no auto refresh."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="analytics.analyticspage",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DashboardC",
        ),
        migrations.DeleteModel(
            name="Widget",
        ),
    ]
