# Generated by Django 6.0.5 on 2026-06-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_remove_widget_dashboardc_analyticspage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analyticswidget",
            name="page",
        ),
        migrations.DeleteModel(
            name="AnalyticsPage",
        ),
        migrations.DeleteModel(
            name="AnalyticsWidget",
        ),
    ]
