# Generated by Django 6.0.6 on 2026-07-26 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reference", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_id", models.CharField(max_length=50, unique=True)),
                (
                    "sample_stage",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "Receipt"),
                            ("TREATMENT", "Treatment"),
                            ("RELEASE", "Release"),
                            ("SOLIDIFICATION", "Solidification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sampling_date", models.DateField()),
                (
                    "sample_mass_kg",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "sample_volume_l",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                ("urgent", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COLLECTED", "Collected"),
                            ("SENT_TO_LAB", "Sent To Lab"),
                            ("RECEIVED_BY_LAB", "Received By Lab"),
                            ("IN_ANALYSIS", "In Analysis"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="SENT_TO_LAB",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "sample_code_barcode",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("lab_received_date", models.DateField(blank=True, null=True)),
                ("lab_comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-urgent", "sampling_date"],
            },
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_date", models.DateField()),
                (
                    "total_alpha",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=20, null=True
                    ),
                ),
                (
                    "total_beta",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=20, null=True
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("is_latest", models.BooleanField(default=True)),
                ("review_date", models.DateField(blank=True, null=True)),
                ("analysis_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analyst",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GammaActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_bq", models.DecimalField(decimal_places=5, max_digits=20)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gamma_activities",
                        to="laboratory.analysis",
                    ),
                ),
                (
                    "radionuclide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reference.nuclides",
                    ),
                ),
            ],
        ),
    ]
