# Generated by Django 6.0.6 on 2026-06-17 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("waste", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Radionuclide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_id", models.CharField(max_length=50, unique=True)),
                (
                    "sample_stage",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "Receipt"),
                            ("TREATMENT", "Treatment"),
                            ("RELEASE", "Release"),
                            ("SOLIDIFICATION", "Solidification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sampling_date", models.DateField()),
                (
                    "sample_mass_kg",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "sample_volume_l",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                ("urgent", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="waste.wastebatch",
                    ),
                ),
                (
                    "collected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="samples_collected",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-urgent", "sampling_date"],
            },
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_date", models.DateField()),
                (
                    "total_alpha",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=20, null=True
                    ),
                ),
                (
                    "total_beta",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=20, null=True
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analyst",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sample",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="laboratory.sample",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GammaActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_bq", models.DecimalField(decimal_places=5, max_digits=20)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gamma_activities",
                        to="laboratory.analysis",
                    ),
                ),
                (
                    "radionuclide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="laboratory.radionuclide",
                    ),
                ),
            ],
            options={
                "unique_together": {("analysis", "radionuclide")},
            },
        ),
    ]
