# Generated by Django 6.0.6 on 2026-07-26 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("laboratory", "0001_initial"),
        ("waste", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="samples",
                to="waste.wastebatch",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="collected_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="samples_collected",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="sample",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis",
                to="laboratory.sample",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gammaactivity",
            unique_together={("analysis", "radionuclide")},
        ),
    ]
