# Generated by Django 6.0.6 on 2026-06-17 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="analysis_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="is_latest",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="review_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_analyses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="lab_comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="lab_received_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="sample_code_barcode",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="sample",
            name="status",
            field=models.CharField(
                choices=[
                    ("COLLECTED", "Collected"),
                    ("SENT_TO_LAB", "Sent To Lab"),
                    ("RECEIVED_BY_LAB", "Received By Lab"),
                    ("IN_ANALYSIS", "In Analysis"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                ],
                default="SENT_TO_LAB",
                max_length=20,
            ),
        ),
    ]
