# Generated by Django 6.0.6 on 2026-09-20 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_initial'),
        ('reference', '0001_initial'),
        ('waste', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['-analysis_date', '-created_at'], 'verbose_name': 'Analysis', 'verbose_name_plural': 'Analyses'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['-urgent', 'sampling_date'], 'verbose_name': 'Sample', 'verbose_name_plural': 'Samples'},
        ),
        migrations.AddField(
            model_name='sample',
            name='description',
            field=models.CharField(blank=True, help_text='For standalone samples not linked to a waste batch.', max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sent_to_lab_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sent To Lab Date'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analysis_date',
            field=models.DateField(verbose_name='Analysis Date'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analysis_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Analysis Notes'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analyst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Analyst'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='is_latest',
            field=models.BooleanField(default=True, verbose_name='Is Latest'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='review_date',
            field=models.DateField(blank=True, null=True, verbose_name='Review Date'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='sample',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='laboratory.sample', verbose_name='Sample'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='total_alpha',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, verbose_name='Total Alpha (Bq)'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='total_beta',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, verbose_name='Total Beta (Bq)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='waste.wastebatch', verbose_name='Waste Batch'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='collected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_collected', to=settings.AUTH_USER_MODEL, verbose_name='Collected By'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='lab_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Lab Comments'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='lab_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='Lab Received Date'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_code_barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Sample ID'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_mass_kg',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Sample Mass (kg)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_stage',
            field=models.CharField(choices=[('RECEIPT', 'Receipt'), ('TREATMENT', 'Treatment'), ('RELEASE', 'Release'), ('SOLIDIFICATION', 'Solidification')], max_length=20, verbose_name='Sample Stage'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_volume_l',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Sample Volume (L)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sampling_date',
            field=models.DateField(verbose_name='Sampling Date'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('COLLECTED', 'Collected'), ('SENT_TO_LAB', 'Sent To Lab'), ('RECEIVED_BY_LAB', 'Received By Lab'), ('IN_ANALYSIS', 'In Analysis'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='COLLECTED', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='urgent',
            field=models.BooleanField(default=False, verbose_name='Urgent'),
        ),
        migrations.CreateModel(
            name='NuclideActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radiation_type', models.CharField(choices=[('ALPHA', 'Alpha'), ('BETA', 'Beta'), ('GAMMA', 'Gamma')], default='GAMMA', max_length=10, verbose_name='Radiation Type')),
                ('activity_bq', models.DecimalField(decimal_places=5, max_digits=20, verbose_name='Activity (Bq)')),
                ('uncertainty_bq', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, verbose_name='Uncertainty (Bq)')),
                ('mda_bq', models.DecimalField(blank=True, decimal_places=5, help_text='Minimum detectable activity.', max_digits=20, null=True, verbose_name='MDA (Bq)')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuclide_activities', to='laboratory.analysis', verbose_name='Analysis')),
                ('radionuclide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.nuclides', verbose_name='Radionuclide')),
            ],
            options={
                'verbose_name': 'Nuclide Activity',
                'verbose_name_plural': 'Nuclide Activities',
                'unique_together': {('analysis', 'radionuclide', 'radiation_type')},
            },
        ),
        migrations.DeleteModel(
            name='GammaActivity',
        ),
    ]
