# Generated by Django 6.0.5 on 2026-06-20 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_remove_dsrs_child_remove_dsrs_parent_and_more"),
        ("laboratory", "0002_analysis_analysis_notes_analysis_is_latest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gammaactivity",
            name="radionuclide",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="dashboard.nuclides"
            ),
        ),
        migrations.DeleteModel(
            name="Radionuclide",
        ),
    ]
