# Generated by Django 6.0.6 on 2026-09-26 05:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_alter_analysis_options_alter_sample_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='sample_volume_l',
        ),
        migrations.AddField(
            model_name='analysis',
            name='alpha_mda',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, verbose_name='MDA Alpha'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='alpha_uncertainty',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, verbose_name='Alpha uncertainty ±2s'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='beta_mda',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, verbose_name='MDA Beta'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='beta_uncertainty',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, verbose_name='Beta uncertainty ±2s'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='counting_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Counting Duration (seconds)'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='detector_type',
            field=models.CharField(choices=[('ALPHABETA', 'Gas proportional detector'), ('HPGE', 'Gamma spectrometry / HPGe')], default=django.utils.timezone.now, max_length=30, verbose_name='Detector Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='applicant_name',
            field=models.CharField(blank=True, help_text='Name of the applicant company or unit.', max_length=255, null=True, verbose_name='Applicant name'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sample type'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_volume_ml',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Sample Volume (ml)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sampling_location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sampling location'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sampling_date',
            field=models.DateTimeField(verbose_name='Sampling Date'),
        ),
        migrations.CreateModel(
            name='AnalysisApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('signed_date', models.DateField(null=True)),
                ('signature', models.ImageField(null=True, upload_to='laboratory/signatures/')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='laboratory.analysis')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='laboratory/spectra/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='laboratory.analysis')),
            ],
        ),
    ]
