# Generated by Django 6.0.6 on 2026-07-17 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0003_alter_gammaactivity_radionuclide_delete_radionuclide"),
        ("reference", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gammaactivity",
            name="radionuclide",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="reference.nuclides"
            ),
        ),
    ]
