# Generated by Django 6.0.6 on 2026-09-28 05:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "laboratory",
            "0004_remove_sample_sample_volume_l_analysis_alpha_mda_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysisapproval",
            options={
                "ordering": ["order"],
                "verbose_name": "Lab Approval",
                "verbose_name_plural": "Lab Approvals",
            },
        ),
        migrations.AddField(
            model_name="analysisapproval",
            name="comments",
            field=models.TextField(blank=True, verbose_name="Comments"),
        ),
        migrations.AddField(
            model_name="analysisapproval",
            name="order",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="analysisapproval",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=15,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="analysisattachment",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("REPORT", "Generated Report"),
                    ("SPECTRUM", "Spectrum"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=15,
                verbose_name="Attachment Type",
            ),
        ),
        migrations.AddField(
            model_name="analysisattachment",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analysisattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="analysisapproval",
            name="analysis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to="laboratory.analysis",
            ),
        ),
        migrations.AlterField(
            model_name="analysisapproval",
            name="role",
            field=models.CharField(
                choices=[
                    ("ANALYST", "Analysis Lab Expert"),
                    ("LAB_MANAGER", "Lab Manager"),
                    ("OPS_MANAGER", "Operations / Operations Control Manager"),
                ],
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="analysisapproval",
            name="signature",
            field=models.ImageField(
                blank=True, null=True, upload_to="laboratory/signatures/"
            ),
        ),
        migrations.AlterField(
            model_name="analysisapproval",
            name="signed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="analysisapproval",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="analysisattachment",
            name="analysis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="laboratory.analysis",
            ),
        ),
        migrations.AlterField(
            model_name="analysisattachment",
            name="description",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="analysisattachment",
            name="file",
            field=models.FileField(
                upload_to="laboratory/attachments/", verbose_name="File"
            ),
        ),
        migrations.CreateModel(
            name="AlphaBetaCountingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_id",
                    models.CharField(max_length=50, unique=True, verbose_name="Run ID"),
                ),
                ("run_date", models.DateField(verbose_name="Counting Date")),
                (
                    "counting_duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Counting Duration (seconds)",
                    ),
                ),
                (
                    "alpha_mda_mbq",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=20,
                        null=True,
                        verbose_name="MDA Alpha (mBq)",
                    ),
                ),
                (
                    "beta_mda_mbq",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=20,
                        null=True,
                        verbose_name="MDA Beta (mBq)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "approved",
                    models.BooleanField(default=False, verbose_name="Approved"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="counting_runs_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alpha/Beta Counting Run",
                "verbose_name_plural": "Alpha/Beta Counting Runs",
                "ordering": ["-run_date", "-id"],
            },
        ),
        migrations.AddField(
            model_name="analysis",
            name="counting_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analyses",
                to="laboratory.alphabetacountingrun",
                verbose_name="Counting Run",
            ),
        ),
        migrations.AddField(
            model_name="analysisapproval",
            name="counting_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to="laboratory.alphabetacountingrun",
            ),
        ),
        migrations.AddField(
            model_name="analysisattachment",
            name="counting_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="laboratory.alphabetacountingrun",
            ),
        ),
    ]
