# Generated by Django 6.0.6 on 2026-09-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0005_alter_analysisapproval_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="analysis_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ALPHABETA", "Gas proportional detector"),
                    ("HPGE", "Gamma spectrometry / HPGe"),
                ],
                default="",
                help_text="Which detector this sample will be counted on — decides which report it gets.",
                max_length=30,
                verbose_name="Analysis type",
            ),
        ),
    ]
