# Generated by Django 6.0.6 on 2026-09-28 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0006_sample_analysis_type"),
        ("waste", "0002_remove_liquidwastedetails_batch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="samples",
                to="waste.wastebatch",
                verbose_name="Waste Batch",
            ),
        ),
    ]
