# Generated by Django 6.0.6 on 2026-09-28 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0007_alter_sample_batch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="analysisapproval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("analysis__isnull", False), ("counting_run__isnull", True)
                    ),
                    models.Q(
                        ("analysis__isnull", True), ("counting_run__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="approval_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisattachment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("analysis__isnull", False), ("counting_run__isnull", True)
                    ),
                    models.Q(
                        ("analysis__isnull", True), ("counting_run__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="attachment_exactly_one_target",
            ),
        ),
    ]
