# Generated by Django 6.0.6 on 2026-09-28 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0008_analysisapproval_approval_exactly_one_target_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="rejected_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Rejected At"
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="samples_rejected",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Rejected By",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="rejection_reason",
            field=models.TextField(
                blank=True, default="", verbose_name="Rejection Reason"
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="rejection_seen",
            field=models.BooleanField(default=True),
        ),
    ]
