# Generated by Django 6.0.6 on 2026-10-03 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0009_sample_rejected_at_sample_rejected_by_and_more"),
        ("reference", "0003_remove_nuclides_emits_alpha_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alphabetacountingrun",
            name="alpha_calibration_nuclide",
            field=models.ForeignKey(
                blank=True,
                help_text="Nuclide this counter's alpha channel was calibrated against. \"Pure alpha\" is reported as this nuclide's equivalent activity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="reference.nuclides",
                verbose_name="Alpha Calibration Nuclide",
            ),
        ),
        migrations.AddField(
            model_name="alphabetacountingrun",
            name="alpha_efficiency_correction_factor",
            field=models.FloatField(
                blank=True,
                help_text="Optional manual multiplier for pure alpha — only if you've independently determined the efficiency ratio between the calibration nuclide and whatever you believe actually dominates the unidentified fraction. Leave blank for no correction (recommended unless you have that data).",
                null=True,
                verbose_name="Alpha Efficiency Correction Factor",
            ),
        ),
        migrations.AddField(
            model_name="alphabetacountingrun",
            name="beta_calibration_nuclide",
            field=models.ForeignKey(
                blank=True,
                help_text="Same idea, for the beta channel.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="reference.nuclides",
                verbose_name="Beta Calibration Nuclide",
            ),
        ),
        migrations.AddField(
            model_name="alphabetacountingrun",
            name="beta_efficiency_correction_factor",
            field=models.FloatField(
                blank=True,
                help_text="Same idea, for pure beta.",
                null=True,
                verbose_name="Beta Efficiency Correction Factor",
            ),
        ),
    ]
