# Generated by Django 6.0.6 on 2026-10-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0010_alphabetacountingrun_alpha_calibration_nuclide_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alphabetacountingrun",
            name="applicant_name",
            field=models.CharField(
                blank=True,
                help_text="Printed on the report header. Leave blank to fall back to listing the applicant names recorded on this run's own samples.",
                max_length=255,
                null=True,
                verbose_name="Applicant Name",
            ),
        ),
        migrations.AddField(
            model_name="alphabetacountingrun",
            name="sampling_date_from",
            field=models.DateField(
                blank=True, null=True, verbose_name="Sampling Date (From)"
            ),
        ),
        migrations.AddField(
            model_name="alphabetacountingrun",
            name="sampling_date_to",
            field=models.DateField(
                blank=True,
                help_text="Leave blank if sampling happened on a single date.",
                null=True,
                verbose_name="Sampling Date (To)",
            ),
        ),
        migrations.AddField(
            model_name="alphabetacountingrun",
            name="sampling_location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Sampling Location"
            ),
        ),
    ]
