# Generated by Django 6.0.6 on 2026-10-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0011_alphabetacountingrun_applicant_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alphabetacountingrun",
            name="counting_completed",
            field=models.BooleanField(
                default=False,
                help_text="Set once the lab has entered counting duration and MDAs — distinguishes 'awaiting counting' from 'ready to report' at a glance.",
                verbose_name="Counting Completed",
            ),
        ),
        migrations.AddField(
            model_name="alphabetacountingrun",
            name="sample_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RECEIPT", "Receipt"),
                    ("TREATMENT", "Treatment"),
                    ("RELEASE", "Release"),
                    ("SOLIDIFICATION", "Solidification"),
                ],
                help_text="Applied to every sample added at run creation — they're all collected together.",
                max_length=20,
                null=True,
                verbose_name="Sample Stage",
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="analysis_date",
            field=models.DateField(blank=True, null=True, verbose_name="Analysis Date"),
        ),
    ]
