# Generated by Django 6.0.6 on 2026-10-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0012_alphabetacountingrun_counting_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alphabetacountingrun",
            name="run_date",
            field=models.DateField(null=True, verbose_name="Counting Date"),
        ),
    ]
