# Generated by Django 6.0.6 on 2026-10-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0013_alter_alphabetacountingrun_run_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisattachment",
            name="content_page_count",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Set automatically when the report is generated — how many pages are the actual report, before any signature page. Lets re-signing strip the old signature page and append a fresh one without cutting into real content.",
                null=True,
                verbose_name="Content Page Count",
            ),
        ),
    ]
