# Generated by Django 6.0.6 on 2026-07-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FacilityModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Facility Name",
                    ),
                ),
                (
                    "responsible_person",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Responsible Person",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Telephone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "address1",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Address Line 1",
                    ),
                ),
                (
                    "address2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Address Line 2",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Postal Code"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="National ID"
                    ),
                ),
                (
                    "economic_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Economic Code",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Facility",
                "verbose_name_plural": "Facilities",
                "ordering": ["name"],
            },
        ),
    ]
