# Generated by Django 6.0.6 on 2026-07-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Facility Name"),
                ),
                (
                    "responsible_person",
                    models.CharField(max_length=150, verbose_name="Responsible Person"),
                ),
                (
                    "telephone",
                    models.CharField(max_length=30, verbose_name="Telephone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "address1",
                    models.CharField(max_length=255, verbose_name="Address Line 1"),
                ),
                (
                    "address2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Address Line 2"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Postal Code"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="National ID"
                    ),
                ),
                (
                    "economic_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Economic Code"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Facility",
                "verbose_name_plural": "Facilities",
                "ordering": ["name"],
            },
        ),
    ]
