# Generated by Django 6.0.6 on 2026-07-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="address1",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address Line 1"
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="address2",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address Line 2"
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="economic_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Economic Code"
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Facility Name"
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="national_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="National ID"
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Postal Code"
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="responsible_person",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Responsible Person"
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="telephone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Telephone"
            ),
        ),
    ]
