# Generated by Django 6.0.6 on 2026-08-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilitymodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="facilitymodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AddConstraint(
            model_name="facilitymodel",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_facility_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="facilitymodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("national_id__isnull", False)),
                fields=("national_id",),
                name="unique_facility_national_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="facilitymodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("postal_code__isnull", False)),
                fields=("postal_code",),
                name="unique_facility_postal_code",
            ),
        ),
    ]
