# Generated by Django 6.0.6 on 2026-07-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0002_alter_facility_address1_alter_facility_address2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facility",
            name="is_active",
        ),
    ]
