# Generated by Django 6.0.6 on 2026-08-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0002_alter_facilitymodel_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="facilitymodel",
            name="unique_facility_name",
        ),
        migrations.AddConstraint(
            model_name="facilitymodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("economic_code__isnull", False)),
                fields=("economic_code",),
                name="unique_facility_economic_code",
            ),
        ),
    ]
