# Generated by Django 6.0.6 on 2026-07-28 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicallicensepayment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical License Payment",
                "verbose_name_plural": "historical License Payments",
            },
        ),
        migrations.AlterModelOptions(
            name="licensepayment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "License Payment",
                "verbose_name_plural": "License Payments",
            },
        ),
    ]
