# Generated by Django 6.0.6 on 2026-08-05 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0002_alter_historicallicensepayment_options_and_more"),
        ("operations", "0007_alter_licenseapproval_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallicensepayment",
            name="amount_paid",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Amount Paid",
            ),
        ),
        migrations.AlterField(
            model_name="historicallicensepayment",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="historicallicensepayment",
            name="license",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="operations.licenserequest",
                verbose_name="License",
            ),
        ),
        migrations.AlterField(
            model_name="historicallicensepayment",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="historicallicensepayment",
            name="payment_date",
            field=models.DateField(blank=True, null=True, verbose_name="Payment Date"),
        ),
        migrations.AlterField(
            model_name="historicallicensepayment",
            name="payment_done",
            field=models.BooleanField(default=False, verbose_name="Payment Completed"),
        ),
        migrations.AlterField(
            model_name="historicallicensepayment",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated At"
            ),
        ),
        migrations.AlterField(
            model_name="licensepayment",
            name="amount_paid",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Amount Paid",
            ),
        ),
        migrations.AlterField(
            model_name="licensepayment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="licensepayment",
            name="license",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment",
                to="operations.licenserequest",
                verbose_name="License",
            ),
        ),
        migrations.AlterField(
            model_name="licensepayment",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="licensepayment",
            name="payment_date",
            field=models.DateField(blank=True, null=True, verbose_name="Payment Date"),
        ),
        migrations.AlterField(
            model_name="licensepayment",
            name="payment_done",
            field=models.BooleanField(default=False, verbose_name="Payment Completed"),
        ),
        migrations.AlterField(
            model_name="licensepayment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
