# Generated by Django 6.0.6 on 2026-07-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nuclides",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=8)),
                ("half_life", models.FloatField()),
                ("d_value_bq", models.FloatField()),
                ("atomic_number", models.IntegerField(blank=True, null=True)),
                ("mass_number", models.IntegerField(blank=True, null=True)),
                ("decay_mode", models.CharField(blank=True, max_length=50, null=True)),
                ("decay_constant", models.FloatField(blank=True, null=True)),
                (
                    "specific_activity_bq_per_g",
                    models.FloatField(blank=True, null=True),
                ),
                ("alpha_energy_mev", models.FloatField(blank=True, null=True)),
                ("beta_max_energy_mev", models.FloatField(blank=True, null=True)),
                ("gamma_energy_mev", models.FloatField(blank=True, null=True)),
                ("gamma_yield", models.FloatField(blank=True, null=True)),
                ("neutron_emitter", models.BooleanField(default=False)),
                ("neutron_yield_n_per_s", models.FloatField(blank=True, null=True)),
                (
                    "dose_rate_constant_usv_m2_per_h_gbq",
                    models.FloatField(blank=True, null=True),
                ),
                ("half_value_layer_lead_mm", models.FloatField(blank=True, null=True)),
                (
                    "half_value_layer_concrete_mm",
                    models.FloatField(blank=True, null=True),
                ),
                ("iaea_category", models.IntegerField(blank=True, null=True)),
                (
                    "parent_nuclide",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "daughter_nuclide",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_sealed_source_common", models.BooleanField(default=False)),
            ],
        ),
    ]
