# Generated by Django 6.0.6 on 2026-09-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nuclides",
            name="emits_alpha",
            field=models.BooleanField(
                default=False,
                help_text="This nuclide's own decay includes alpha emission — netted out of gross alpha counting the same way.",
            ),
        ),
        migrations.AddField(
            model_name="nuclides",
            name="emits_beta",
            field=models.BooleanField(
                default=False,
                help_text="This nuclide's own decay includes beta emission (β⁻/β⁺) — used to net its activity out of gross beta counting when it's also identified by gamma spec.",
            ),
        ),
    ]
