# Generated by Django 6.0.6 on 2026-10-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0002_nuclides_emits_alpha_nuclides_emits_beta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nuclides",
            name="emits_alpha",
        ),
        migrations.RemoveField(
            model_name="nuclides",
            name="emits_beta",
        ),
        migrations.AddField(
            model_name="nuclides",
            name="alpha_emission_probability",
            field=models.FloatField(
                blank=True,
                help_text="Same idea, for alpha emission. 1.0 for a pure alpha emitter (Am-241, Ra-226...); the branching fraction for a mixed-mode nuclide; blank if not an alpha emitter.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="nuclides",
            name="beta_emission_probability",
            field=models.FloatField(
                blank=True,
                help_text="Fraction (0-1) of this nuclide's decays that emit a beta particle. 1.0 for a single-mode beta emitter (Cs-137, Co-60, Sr-90...); the real branching fraction for a mixed-mode nuclide (e.g. K-40 = 0.8928, 89.28% beta / 10.72% EC); leave blank if this nuclide doesn't emit beta at all.",
                null=True,
            ),
        ),
    ]
