# Generated by Django 6.0.6 on 2026-10-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0003_remove_nuclides_emits_alpha_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nuclides",
            name="name",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
