# Generated by Django 6.0.6 on 2026-10-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0004_alter_nuclides_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nuclides",
            name="d_value_bq",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nuclides",
            name="half_life",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
