from django.db import models

# Create your models here.
from django.db import models


from utils.fileValidator import validate_attachment
from django.conf import settings

from django.db import models



# =====================================================
# Choices
# =====================================================

class WasteType(models.TextChoices):
    LIQUID = 'LIQUID', 'Liquid'
    SOLID = 'SOLID', 'Solid'


class WasteClass(models.TextChoices):
    VLLW = 'VLLW', 'Very Low Level Waste'
    LLW = 'LLW', 'Low Level Waste'
    ILW = 'ILW', 'Intermediate Level Waste'
    HLW = 'HLW', 'High Level Waste'


class WasteState(models.TextChoices):
    UNPROCESSED = 'UNPROCESSED', 'Unprocessed'
    PROCESSED = 'PROCESSED', 'Processed'
    CONDITIONED = 'CONDITIONED', 'Conditioned'


class Facility(models.TextChoices):
    TEHRAN = 'TEHRAN', 'Tehran'
    KARAJ = 'KARAJ', 'Karaj'
    ANARAK = 'ANARAK', 'Anarak'


class OriginOfWaste(models.TextChoices):
    RECEIVED = 'RECEIVED', 'Received'
    HISTORICAL = 'HISTORICAL', 'Historical'
    GENERATED = 'GENERATED', 'Generated by Home Facility'
    PROCESSING = 'PROCESSING', 'Generated by Processing'


class BatchStatus(models.TextChoices):
    ACTIVE = 'ACTIVE', 'Active'
    RELEASED = 'RELEASED', 'Released'
    CONSUMED = 'CONSUMED', 'Consumed'
    STORED = 'STORED', 'Stored'


class TreatmentOption(models.TextChoices):
    CHEMICAL = 'CHEMICAL', 'Chemical Treatment'
    SEDIMENTATION = 'SEDIMENTATION', 'Sedimentation'
    FILTRATION = 'FILTRATION', 'Filtration'
    CEMENTATION = 'CEMENTATION', 'Cementation'
    INCINERATION = 'INCINERATION', 'Incineration'


# =====================================================
# Main Waste Batch
# =====================================================

class WasteBatch(models.Model):

    waste_id = models.CharField(
        max_length=100,
        unique=True
    )

    waste_type = models.CharField(
        max_length=10,
        choices=WasteType.choices
    )

    waste_class = models.CharField(
        max_length=10,
        choices=WasteClass.choices,
        blank=True,
        null=True
    )

    waste_state = models.CharField(
        max_length=20,
        choices=WasteState.choices,
        default=WasteState.UNPROCESSED
    )

    facility = models.CharField(
        max_length=20,
        choices=Facility.choices
    )

    origin_of_waste = models.CharField(
        max_length=20,
        choices=OriginOfWaste.choices
    )

    date_received = models.DateField()

    origin_facility = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )

    description = models.TextField(
        blank=True,
        null=True
    )

    material = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )

    container_type = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )

    mass_kg = models.DecimalField(
        max_digits=12,
        decimal_places=3,
        blank=True,
        null=True
    )

    volume_m3 = models.DecimalField(
        max_digits=12,
        decimal_places=3,
        blank=True,
        null=True
    )
    current_alpha_bq = models.DecimalField(
    max_digits=20,
    decimal_places=5,
    default=0,
    blank=True,
    null=True
    )

    current_beta_bq = models.DecimalField(
        max_digits=20,
        decimal_places=5,
        default=0,
        blank=True,
        null=True
    )

    current_gamma_bq = models.DecimalField(
        max_digits=20,
        decimal_places=5,
        default=0,
        blank=True,
        null=True
    )

    current_total_activity_bq = models.DecimalField(
        max_digits=20,
        decimal_places=5,
        default=0,
        blank=True,
        null=True
    )

    latest_analysis_date = models.DateField(
        blank=True,
        null=True
    )

    parent_count = models.PositiveIntegerField(
        default=0
    )

    generation_number = models.PositiveIntegerField(
        default=0
    )
    dose_rate_1m = models.DecimalField(
        max_digits=12,
        decimal_places=4,
        blank=True,
        null=True
    )

    dose_rate_surface = models.DecimalField(
        max_digits=12,
        decimal_places=4,
        blank=True,
        null=True
    )

    alpha_contamination = models.DecimalField(
        max_digits=12,
        decimal_places=4,
        blank=True,
        null=True
    )

    beta_gamma_contamination = models.DecimalField(
        max_digits=12,
        decimal_places=4,
        blank=True,
        null=True
    )

    location = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )

    status = models.CharField(
        max_length=20,
        choices=BatchStatus.choices,
        default=BatchStatus.ACTIVE
    )

    is_active = models.BooleanField(
        default=True
    )

    attachment = models.FileField(
        upload_to='attachments/',
        validators=[validate_attachment],
        blank=True,
        null=True
    )

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name='created_batches'
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    updated_at = models.DateTimeField(
        auto_now=True
    )
    @property
    def is_liquid(self):
        return self.waste_type == WasteType.LIQUID


    @property
    def is_solid(self):
        return self.waste_type == WasteType.SOLID


    @property
    def attachment_name(self):

        if self.attachment:

            return self.attachment.name.split("/")[-1]

        return ""
    class Meta:
        ordering = (
            "-created_at",
            "waste_id",)

    def __str__(self):
        return self.waste_id

# Liquid Waste Details

class LiquidWasteDetails(models.Model):

    batch = models.OneToOneField(
        WasteBatch,
        on_delete=models.CASCADE,
        related_name='liquid_details'
    )

    ph = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        blank=True,
        null=True
    )

    density = models.DecimalField(
        max_digits=10,
        decimal_places=4,
        blank=True,
        null=True
    )

    total_solids = models.DecimalField(
        max_digits=10,
        decimal_places=4,
        blank=True,
        null=True
    )

    suspended_solids = models.DecimalField(
        max_digits=10,
        decimal_places=4,
        blank=True,
        null=True
    )

    soluble_solids = models.DecimalField(
        max_digits=10,
        decimal_places=4,
        blank=True,
        null=True
    )

    possible_treatment = models.CharField(
        max_length=30,
        choices=TreatmentOption.choices,
        blank=True,
        null=True
    )

# Conditioning Information
class WasteConditioning(models.Model):

    batch = models.OneToOneField(
        WasteBatch,
        on_delete=models.CASCADE,
        related_name='conditioning'
    )

    pretreatment = models.CharField(
        max_length=30,
        choices=TreatmentOption.choices,
        blank=True,
        null=True)

    treatment = models.CharField(
        max_length=30,
        choices=TreatmentOption.choices,
        blank=True,
        null=True)

    further_conditioning_planned = models.CharField(
        max_length=50,
        blank=True,
        null=True
    )

    conditioning_matrix = models.CharField(
        max_length=50,
        blank=True,
        null=True
    )

    waste_to_matrix_ratio = models.DecimalField(
        max_digits=10,
        decimal_places=4,
        blank=True,
        null=True
    )




class BatchActivitySnapshot(models.Model):

    batch = models.ForeignKey(
        WasteBatch,
        on_delete=models.CASCADE,
        related_name='activity_snapshots'
    )

    analysis = models.ForeignKey(
        'laboratory.Analysis',
        on_delete=models.CASCADE
    )

    alpha_bq = models.DecimalField(
        max_digits=20,
        decimal_places=5
    )

    beta_bq = models.DecimalField(
        max_digits=20,
        decimal_places=5
    )

    gamma_bq = models.DecimalField(
        max_digits=20,
        decimal_places=5
    )

    total_activity_bq = models.DecimalField(
        max_digits=20,
        decimal_places=5
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    class Meta:
        ordering = ['-created_at']