from functools import cached_property

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from simple_history.models import HistoricalRecords

from common.utils.fileValidator import validate_attachment
from facilities.models import FacilityModel


# =====================================================
# Choices
# =====================================================

class WasteType(models.TextChoices):
    LIQUID = "LIQUID", _("Liquid")
    SOLID = "SOLID", _("Solid")


class WasteClass(models.TextChoices):
    VLLW = "VLLW", _("Very Low Level Waste")
    LLW = "LLW", _("Low Level Waste")
    ILW = "ILW", _("Intermediate Level Waste")
    HLW = "HLW", _("High Level Waste")


class WasteState(models.TextChoices):
    UNPROCESSED = "UNPROCESSED", _("Unprocessed")
    PROCESSED = "PROCESSED", _("Processed")


class OriginOfWaste(models.TextChoices):
    RECEIVED = "RECEIVED", _("Received")
    HISTORICAL = "HISTORICAL", _("Historical")
    GENERATED = "GENERATED", _("Generated by Home Facility")
    PROCESSING = "PROCESSING", _("Generated by Processing")


class BatchStatus(models.TextChoices):
    STORED = "STORED", _("Stored")
    IN_TREATMENT = "IN_TREATMENT", _("In Treatment")
    TRANSFERRED = "TRANSFERRED", _("Transferred")
    RELEASED = "RELEASED", _("Released")
    DISPOSED = "DISPOSED", _("Disposed")
    CONSUMED = "CONSUMED", _("Consumed (merged/split/conditioned into another batch)")


class PreTreatmentOption(models.TextChoices):
    DISMANTLING = "DISMANTLING", _("Dismantling")
    SAWING = "SAWING", _("Sawing")
    CHEMICAL = "CHEMICAL", _("Chemical Adjustment")
    SHREDDING = "SHREDDING", _("Shredding")
    CRUSHING = "CRUSHING", _("Crushing")
    SEGREGATION = "SEGREGATION", _("Segregation")


class TreatmentOption(models.TextChoices):
    CHEMICAL = "CHEMICAL", _("Chemical Precipitation")
    EVAPORATION = "EVAPORATION", _("Evaporation")
    ION_EXCHANGE = "ION_EXCHANGE", _("Ion Exchange")
    COMPACTION = "COMPACTION", _("Compaction")
    CONDITIONING = "CONDITIONING", _("Conditioning")
    SEDIMENTATION = "SEDIMENTATION", _("Sedimentation")
    FILTRATION = "FILTRATION", _("Filtration")
    CEMENTATION = "CEMENTATION", _("Cementation")
    REMOVAL = "REMOVAL", _("Removal")
    INCINERATION = "INCINERATION", _("Incineration")


class WasteMovementType(models.TextChoices):
    RECEIVE = "RECEIVE", _("Receive")
    TRANSFER = "TRANSFER", _("Transfer")
    STORE = "STORE", _("Store")
    TREATMENT = "TREATMENT", _("Send to Treatment")
    RELEASE = "RELEASE", _("Release")
    DISPOSAL = "DISPOSAL", _("Disposal")
    MERGE = "MERGE", _("Merge")
    SPLIT = "SPLIT", _("Split")
    CONDITIONING = "CONDITIONING", _("Conditioning")


MOVEMENT_TO_STATUS = {
    WasteMovementType.RECEIVE: BatchStatus.STORED,
    WasteMovementType.STORE: BatchStatus.STORED,
    WasteMovementType.TRANSFER: BatchStatus.TRANSFERRED,
    WasteMovementType.TREATMENT: BatchStatus.IN_TREATMENT,
    WasteMovementType.RELEASE: BatchStatus.RELEASED,
    WasteMovementType.DISPOSAL: BatchStatus.DISPOSED,
    WasteMovementType.MERGE: BatchStatus.CONSUMED,
    WasteMovementType.SPLIT: BatchStatus.CONSUMED,
    WasteMovementType.CONDITIONING: BatchStatus.CONSUMED,
}


class LineageOperation(models.TextChoices):
    MERGE = "MERGE", _("Merge")
    SPLIT = "SPLIT", _("Split")
    CONDITIONING = "CONDITIONING", _("Conditioning")


# =====================================================
# Main Waste Batch
#
# Deliberately FLAT (one model, nullable type/state-specific columns),
# same as DSRS. Which fields apply is a UI concern (forms.py shows/hides
# per waste_type + waste_state); clean() below only guards the rules that
# must never be violated whatever the UI does.
# =====================================================

LIQUID_ONLY_FIELDS = ("ph", "density", "total_solids", "suspended_solids", "soluble_solids")
PROCESSED_ONLY_FIELDS = ("pretreatment", "treatment", "package_type", "waste_matrix")


class WasteBatch(models.Model):

    waste_id = models.CharField(_("Waste ID"), max_length=100, unique=True)

    waste_type = models.CharField(_("Waste Type"), max_length=10, choices=WasteType.choices)
    waste_class = models.CharField(_("Waste Class"), max_length=10, choices=WasteClass.choices, blank=True, null=True)
    waste_state = models.CharField(
        _("Waste State"), max_length=20, choices=WasteState.choices, default=WasteState.UNPROCESSED
    )

    facility = models.ForeignKey(
        FacilityModel,
        verbose_name=_("Current Facility"),
        on_delete=models.PROTECT,
        related_name="waste_batches",
    )
    origin_facility = models.ForeignKey(
        FacilityModel,
        verbose_name=_("Origin Facility"),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="originated_waste_batches",
    )

    origin_of_waste = models.CharField(_("Origin of Waste"), max_length=20, choices=OriginOfWaste.choices)
    date_received = models.DateField(_("Date Received"), null=True, blank=True)

    description = models.TextField(_("Description"), blank=True, null=True)
    waste_arising_from = models.CharField(_("Waste Arising From"), max_length=100, blank=True, null=True)
    material = models.CharField(_("Material"), max_length=100, blank=True, null=True)
    container_type = models.CharField(_("Container Type"), max_length=100, blank=True, null=True)

    # NEW
    waste_appearance = models.CharField(
        _("Waste Appearance"), max_length=255, blank=True, null=True,
        help_text=_("Physical appearance: colour, clarity, texture, visible solids…"),
    )

    mass_kg = models.DecimalField(
        _("Mass (kg)"), max_digits=12, decimal_places=3, blank=True, null=True,
        help_text=_("Total mass of the batch as held (including packaging, if any)."),
    )
    volume_m3 = models.DecimalField(_("Volume (m³)"), max_digits=12, decimal_places=3, blank=True, null=True)

    # ---- Radiological ----
    dose_rate_surface_uSv = models.DecimalField(
        _("Surface Dose Rate (µSv/h)"), max_digits=12, decimal_places=3, blank=True, null=True
    )
    dose_rate_1m_uSv = models.DecimalField(
        _("Dose Rate @ 1m (µSv/h)"), max_digits=12, decimal_places=3, blank=True, null=True
    )
    dose_rate_date = models.DateField(_("Dose Measurement Date"), null=True, blank=True)

    alpha_contamination_bq_cm2 = models.DecimalField(
        _("Alpha Contamination (Bq/cm²)"), max_digits=12, decimal_places=5, blank=True, null=True
    )
    beta_gamma_contamination_bq_cm2 = models.DecimalField(
        _("Beta/Gamma Contamination (Bq/cm²)"), max_digits=20, decimal_places=5, blank=True, null=True
    )

    # Activity figures are NOT stored: they're computed from the latest
    # laboratory Analysis (see the properties below).

    # ---- LIQUID only ----
    ph = models.DecimalField(_("pH"), max_digits=5, decimal_places=2, blank=True, null=True)
    density = models.DecimalField(_("Density"), max_digits=10, decimal_places=4, blank=True, null=True)
    total_solids = models.DecimalField(_("Total Solids"), max_digits=10, decimal_places=4, blank=True, null=True)
    suspended_solids = models.DecimalField(
        _("Suspended Solids"), max_digits=10, decimal_places=4, blank=True, null=True
    )
    soluble_solids = models.DecimalField(_("Soluble Solids"), max_digits=10, decimal_places=4, blank=True, null=True)

    # ---- UNPROCESSED only ----
    possible_pretreatment = models.CharField(
        _("Possible Pre-Treatment"), max_length=30, choices=PreTreatmentOption.choices, blank=True, null=True
    )
    possible_treatment = models.CharField(
        _("Possible Treatment"), max_length=30, choices=TreatmentOption.choices, blank=True, null=True
    )

    # ---- PROCESSED only ----
    pretreatment = models.CharField(
        _("Pre-Treatment Applied"), max_length=30, choices=PreTreatmentOption.choices, blank=True, null=True
    )
    treatment = models.CharField(
        _("Treatment Applied"), max_length=30, choices=TreatmentOption.choices, blank=True, null=True
    )
    package_type = models.CharField(_("Package Type"), max_length=100, blank=True, null=True)
    waste_matrix = models.CharField(_("Waste Matrix"), max_length=100, blank=True, null=True)

    # ---- PROCESSED + LIQUID only ----
    waste_to_matrix_ratio = models.DecimalField(
        _("Waste to Matrix Ratio"), max_digits=10, decimal_places=4, blank=True, null=True
    )
    waste_mass_kg = models.DecimalField(
        _("Waste Mass (kg)"), max_digits=12, decimal_places=3, blank=True, null=True,
        help_text=_("Mass of the waste itself, without matrix/package."),
    )
    package_mass_kg = models.DecimalField(
        _("Package Mass (kg)"), max_digits=12, decimal_places=3, blank=True, null=True
    )
    package_volume_m3 = models.DecimalField(
        _("Package Volume (m³)"), max_digits=12, decimal_places=3, blank=True, null=True
    )

    # ---- Admin ----
    location = models.CharField(_("Storage Location"), max_length=100, blank=True, null=True)
    status = models.CharField(
        _("Status"), max_length=20, choices=BatchStatus.choices, default=BatchStatus.STORED
    )
    status_date = models.DateField(_("Status Date"), null=True, blank=True)

    attachment = models.FileField(
        _("Attachment"),
        upload_to="waste/attachments/",
        validators=[validate_attachment],
        blank=True,
        null=True,
    )

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Created By"),
        on_delete=models.SET_NULL,
        null=True,
        related_name="created_batches",
    )
    created_at = models.DateTimeField(_("Created At"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Updated At"), auto_now=True)

    history = HistoricalRecords()

    class Meta:
        ordering = ("-created_at", "waste_id")
        verbose_name = _("Waste Batch")
        verbose_name_plural = _("Waste Batches")
        indexes = [
            models.Index(fields=["status"]),
            models.Index(fields=["facility", "status"]),
            models.Index(fields=["waste_type", "waste_state"]),
        ]

    def __str__(self):
        return self.waste_id

    # =====================================================
    # Validation — only the rules that must hold whatever the UI does.
    # Raised as NON-field errors on purpose, so it is safe even when a
    # ModelForm doesn't include some of these fields.
    # =====================================================

    def clean(self):
        super().clean()
        problems = []

        if self.waste_state == WasteState.PROCESSED:
            if not self.treatment:
                problems.append(_("A processed batch must have the treatment that was applied."))
            if not self.waste_matrix:
                problems.append(_("A processed batch must have a waste matrix."))
        else:
            filled = [f for f in PROCESSED_ONLY_FIELDS if getattr(self, f)]
            if filled:
                problems.append(_("Pre-treatment/treatment applied, package type and waste matrix only apply to processed batches."))

        if self.waste_type != WasteType.LIQUID:
            if any(getattr(self, f) is not None for f in LIQUID_ONLY_FIELDS):
                problems.append(_("pH, density and solids only apply to liquid waste."))

        if problems:
            raise ValidationError(problems)

    # =====================================================
    # Activity — read from the laboratory app, never stored here.
    # Imports are LOCAL because laboratory.models imports WasteBatch.
    #
    # `latest_analysis` is cached per instance (one query per batch per
    # request instead of one per property) and picks the newest analysis
    # by analysis date — it no longer depends on Analysis.is_latest, which
    # flips back whenever an OLD analysis is re-saved. Its per-nuclide rows
    # are prefetched, so everything below reuses them with no extra queries.
    #
    # After creating a new analysis inside the same request, call
    # batch.refresh_activity() to drop the cache.
    # =====================================================

    @cached_property
    def latest_analysis(self):
        from laboratory.models import Analysis
        return (
            Analysis.objects
            .filter(sample__batch=self)
            .prefetch_related("nuclide_activities__radionuclide")
            .order_by("-analysis_date", "-created_at", "-id")
            .first()
        )

    def refresh_activity(self):
        self.__dict__.pop("latest_analysis", None)

    @property
    def total_alpha_bq(self):
        analysis = self.latest_analysis
        return analysis.total_alpha if analysis else None

    @property
    def total_beta_bq(self):
        analysis = self.latest_analysis
        return analysis.total_beta if analysis else None

    def nuclide_activities(self):
        """Per-nuclide activities (alpha/beta/gamma) from the latest analysis."""
        analysis = self.latest_analysis
        return list(analysis.nuclide_activities.all()) if analysis else []

    def _decayed_total(self, activities):
        """Sum of decay-corrected activities, or None when there is nothing to sum.
        (A genuine 0 stays 0 — only 'no data' is None.)"""
        total, seen = 0.0, False
        for na in activities:
            value = na.current_activity_bq()
            if value is not None:
                total += value
                seen = True
        return total if seen else None

    def current_total_activity_bq(self):
        return self._decayed_total(self.nuclide_activities())

    def current_gamma_bq(self):
        from laboratory.models import RadiationType
        return self._decayed_total(
            na for na in self.nuclide_activities() if na.radiation_type == RadiationType.GAMMA
        )

    @property
    def current_total_activity_bq_value(self):
        value = self.current_total_activity_bq()
        return round(value, 3) if value is not None else None

    @property
    def current_gamma_bq_value(self):
        value = self.current_gamma_bq()
        return round(value, 3) if value is not None else None

    @property
    def nuclide_summary(self):
        """Short 'Cs-137, Co-60' style string for the inventory table."""
        names = []
        for na in self.nuclide_activities():
            name = str(na.radionuclide)
            if name not in names:
                names.append(name)
        return ", ".join(names)

    # =====================================================
    # Movements
    # =====================================================

    @property
    def last_movement(self):
        return self.movements.order_by("-movement_date", "-id").first()

    def register_movement(
        self,
        movement_type,
        to_facility,
        from_facility=None,
        performed_by=None,
        remarks="",
        movement_date=None,
        mass_kg=None,
        volume_m3=None,
    ):
        """Mirrors DSRS.register_movement: records the movement AND applies
        its implied status/facility change in one place.

        NOTE: mass_kg / volume_m3 are recorded on the movement only. They do
        NOT reduce the batch — a partial removal must be done as a SPLIT
        (which creates child batches through WasteBatchLineage)."""

        if movement_date is None:
            movement_date = timezone.now().date()

        movement = self.movements.create(
            movement_type=movement_type,
            from_facility=from_facility or self.facility,
            to_facility=to_facility,
            movement_date=movement_date,
            performed_by=performed_by,
            mass_kg=mass_kg,
            volume_m3=volume_m3,
            remarks=remarks,
        )

        if to_facility:
            self.facility = to_facility
        self.status = MOVEMENT_TO_STATUS.get(movement_type, self.status)
        self.status_date = movement_date
        # updated_at must be listed, otherwise auto_now is skipped by update_fields
        self.save(update_fields=["facility", "status", "status_date", "updated_at"])

        return movement


class WasteMovement(models.Model):

    batch = models.ForeignKey(
        WasteBatch, verbose_name=_("Batch"), on_delete=models.CASCADE, related_name="movements"
    )

    movement_type = models.CharField(_("Movement Type"), max_length=20, choices=WasteMovementType.choices)

    from_facility = models.ForeignKey(
        FacilityModel, verbose_name=_("From Facility"), null=True, blank=True,
        related_name="+", on_delete=models.SET_NULL,
    )
    to_facility = models.ForeignKey(
        FacilityModel, verbose_name=_("To Facility"), null=True, blank=True,
        related_name="+", on_delete=models.SET_NULL,
    )

    movement_date = models.DateField(_("Movement Date"))

    mass_kg = models.DecimalField(_("Mass Moved (kg)"), max_digits=12, decimal_places=3, blank=True, null=True)
    volume_m3 = models.DecimalField(_("Volume Moved (m³)"), max_digits=12, decimal_places=3, blank=True, null=True)

    performed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name=_("Performed By"), on_delete=models.SET_NULL, null=True,
    )

    remarks = models.TextField(_("Remarks"), blank=True)
    created_at = models.DateTimeField(_("Created At"), auto_now_add=True)

    class Meta:
        ordering = ["movement_date", "id"]
        verbose_name = _("Waste Movement")
        verbose_name_plural = _("Waste Movements")
        indexes = [
            models.Index(fields=["batch"]),
            models.Index(fields=["movement_date"]),
            models.Index(fields=["movement_type"]),
        ]

    def __str__(self):
        return f"{self.get_movement_type_display()} {self.from_facility} → {self.to_facility}"


class WasteMovementAttachment(models.Model):

    movement = models.ForeignKey(
        WasteMovement, verbose_name=_("Movement"), on_delete=models.CASCADE, related_name="attachments"
    )
    file = models.FileField(
        _("Attachment File"), upload_to="waste/movements/", validators=[validate_attachment]
    )
    uploaded_at = models.DateTimeField(_("Uploaded At"), auto_now_add=True)

    class Meta:
        verbose_name = _("Waste Movement Attachment")
        verbose_name_plural = _("Waste Movement Attachments")


# =====================================================
# Lineage — merge / split / conditioning
#   MERGE        : many parents -> one child
#   SPLIT        : one parent   -> many children
#   CONDITIONING : one parent   -> one child (PROCESSED SOLID)
# =====================================================

class WasteBatchLineage(models.Model):

    parent = models.ForeignKey(
        WasteBatch, verbose_name=_("Parent Batch"), on_delete=models.PROTECT, related_name="child_links"
    )
    child = models.ForeignKey(
        WasteBatch, verbose_name=_("Resulting Batch"), on_delete=models.CASCADE, related_name="parent_links"
    )

    operation = models.CharField(_("Operation"), max_length=20, choices=LineageOperation.choices)

    mass_kg = models.DecimalField(
        _("Mass Contributed (kg)"), max_digits=12, decimal_places=3, blank=True, null=True
    )
    volume_m3 = models.DecimalField(
        _("Volume Contributed (m³)"), max_digits=12, decimal_places=3, blank=True, null=True
    )

    performed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name=_("Performed By"), on_delete=models.SET_NULL, null=True,
    )
    performed_at = models.DateTimeField(_("Performed At"), auto_now_add=True)
    remarks = models.TextField(_("Remarks"), blank=True)

    class Meta:
        ordering = ["-performed_at"]
        verbose_name = _("Waste Batch Lineage")
        verbose_name_plural = _("Waste Batch Lineage")

    def __str__(self):
        return f"{self.get_operation_display()}: {self.parent} → {self.child}"