# Generated by Django 6.0.6 on 2026-07-26 08:10

import common.utils.fileValidator
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contract", "0001_initial"),
        ("facilities", "0001_initial"),
        ("reference", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HideShowFilterT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent", models.CharField(max_length=50)),
                ("key", models.CharField(max_length=50)),
                ("value", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModelFilterT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent", models.CharField(max_length=50)),
                ("key", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DSRS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Source_Type",
                    models.CharField(
                        choices=[("SRS", "SRS"), ("DSRS", "DSRS")],
                        default="DSRS",
                        max_length=10,
                    ),
                ),
                ("Sso_Code", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "Origin_Type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Received", "Received"),
                            ("Historical", "Historical"),
                            ("SRS", "SRS"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("Date_received", models.DateField(blank=True, null=True)),
                ("is_divisible", models.BooleanField(default=False)),
                ("source_count", models.PositiveIntegerField(default=1)),
                ("available_count", models.PositiveIntegerField(default=1)),
                ("Location", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "Status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Purchased", "Purchased"),
                            ("In Use", "In Use"),
                            ("Stored", "Stored"),
                            ("Reused", "Reused"),
                            ("Recycled", "Recycled"),
                            ("Disposed", "Disposed"),
                            ("Loaned", "Loaned"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("Status_Date", models.DateField(blank=True, null=True)),
                (
                    "Responsible_Person",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("activity_input", models.FloatField(blank=True, null=True)),
                (
                    "activity_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bq", "Bq"),
                            ("KBq", "KBq"),
                            ("MBq", "MBq"),
                            ("GBq", "GBq"),
                            ("Ci", "Ci"),
                            ("mCi", "mCi"),
                            ("uCi", "uCi"),
                            ("nCi", "nCi"),
                        ],
                        default="Bq",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("Activity_reference_date", models.DateField(blank=True, null=True)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("Dose_rate_surface_uSv", models.FloatField(blank=True, null=True)),
                ("Dose_rate_1m_uSv", models.FloatField(blank=True, null=True)),
                ("Dose_rate_measurement_date", models.DateField(blank=True, null=True)),
                (
                    "source_state",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("Contaminated", "Contaminated")],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("contamination_bq_cm2", models.FloatField(blank=True, null=True)),
                (
                    "Source_Physical_Form",
                    models.CharField(
                        blank=True,
                        choices=[("Solid", "Solid"), ("Liquid", "Liquid")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "Source_Manufacturer",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "Source_Model",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "Source_Practice",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "Device_Manufacturer",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "Device_Model",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "Device_Serial_Number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "Container_Type",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("Dimension", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "Attachments",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="DSRS_Doc",
                        validators=[common.utils.fileValidator.validate_attachment],
                    ),
                ),
                ("Comment", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("initial_activity_bq", models.FloatField(blank=True, null=True)),
                (
                    "Facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Source_Facility",
                        to="facilities.facilitymodel",
                    ),
                ),
                (
                    "Nuclide",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reference.nuclides",
                    ),
                ),
                (
                    "Origin_Facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Origin_Facility",
                        to="facilities.facilitymodel",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contract.licensecontract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="dashboard.dsrs",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DSRSImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="dsrs_images/",
                        validators=[common.utils.fileValidator.validate_attachment],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dsrs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dsrs_images",
                        to="dashboard.dsrs",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalDSRS",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "Source_Type",
                    models.CharField(
                        choices=[("SRS", "SRS"), ("DSRS", "DSRS")],
                        default="DSRS",
                        max_length=10,
                    ),
                ),
                ("Sso_Code", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "Origin_Type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Received", "Received"),
                            ("Historical", "Historical"),
                            ("SRS", "SRS"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("Date_received", models.DateField(blank=True, null=True)),
                ("is_divisible", models.BooleanField(default=False)),
                ("source_count", models.PositiveIntegerField(default=1)),
                ("available_count", models.PositiveIntegerField(default=1)),
                ("Location", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "Status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Purchased", "Purchased"),
                            ("In Use", "In Use"),
                            ("Stored", "Stored"),
                            ("Reused", "Reused"),
                            ("Recycled", "Recycled"),
                            ("Disposed", "Disposed"),
                            ("Loaned", "Loaned"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("Status_Date", models.DateField(blank=True, null=True)),
                (
                    "Responsible_Person",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("activity_input", models.FloatField(blank=True, null=True)),
                (
                    "activity_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bq", "Bq"),
                            ("KBq", "KBq"),
                            ("MBq", "MBq"),
                            ("GBq", "GBq"),
                            ("Ci", "Ci"),
                            ("mCi", "mCi"),
                            ("uCi", "uCi"),
                            ("nCi", "nCi"),
                        ],
                        default="Bq",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("Activity_reference_date", models.DateField(blank=True, null=True)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("Dose_rate_surface_uSv", models.FloatField(blank=True, null=True)),
                ("Dose_rate_1m_uSv", models.FloatField(blank=True, null=True)),
                ("Dose_rate_measurement_date", models.DateField(blank=True, null=True)),
                (
                    "source_state",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("Contaminated", "Contaminated")],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("contamination_bq_cm2", models.FloatField(blank=True, null=True)),
                (
                    "Source_Physical_Form",
                    models.CharField(
                        blank=True,
                        choices=[("Solid", "Solid"), ("Liquid", "Liquid")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "Source_Manufacturer",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "Source_Model",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "Source_Practice",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "Device_Manufacturer",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "Device_Model",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "Device_Serial_Number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "Container_Type",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("Dimension", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "Attachments",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[common.utils.fileValidator.validate_attachment],
                    ),
                ),
                ("Comment", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("initial_activity_bq", models.FloatField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "Facility",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="facilities.facilitymodel",
                    ),
                ),
                (
                    "Nuclide",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="reference.nuclides",
                    ),
                ),
                (
                    "Origin_Facility",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="facilities.facilitymodel",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contract.licensecontract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_from",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dashboard.dsrs",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical dsrs",
                "verbose_name_plural": "historical dsrss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SourceMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("ISSUE", "Issue"),
                            ("RETURN", "Return"),
                            ("REUSE", "Reuse"),
                            ("RECYCLE", "Recycle"),
                            ("DISPOSAL", "Disposal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("movement_date", models.DateField()),
                ("remarks", models.TextField(blank=True)),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contract.licensecontract",
                    ),
                ),
                (
                    "from_facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="facilities.facilitymodel",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dashboard.dsrs"
                    ),
                ),
                (
                    "to_facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="facilities.facilitymodel",
                    ),
                ),
            ],
        ),
    ]
