# Generated by Django 6.0.5 on 2026-06-02 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HideShowFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent", models.CharField(max_length=50)),
                ("key", models.CharField(max_length=50)),
                ("value", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModelFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent", models.CharField(max_length=50)),
                ("key", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Nuclides",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=8)),
                ("half_life", models.FloatField()),
                ("d_value_bq", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="DSRS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Irwa_Code", models.CharField(max_length=15)),
                ("Sso_Code", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "Facility",
                    models.CharField(
                        choices=[
                            ("IRWA", "Tehran Site"),
                            ("KJ", "Karaj Site"),
                            ("AK", "Anarak Site"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "Origin_Type",
                    models.CharField(
                        choices=[
                            ("Received", "Received"),
                            ("Historical", "Historical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("Date_received", models.DateField()),
                ("Origin_Facility", models.CharField(max_length=250)),
                ("Location", models.CharField(max_length=20)),
                (
                    "Status",
                    models.CharField(
                        choices=[("Stored", "Stored"), ("Transferred", "Transferred")],
                        max_length=15,
                    ),
                ),
                ("Status_Date", models.DateField()),
                (
                    "Responsible_Person",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("activity_input", models.FloatField(blank=True, null=True)),
                (
                    "activity_unit",
                    models.CharField(
                        choices=[
                            ("Bq", "Bq"),
                            ("kBq", "kBq"),
                            ("MBq", "MBq"),
                            ("GBq", "GBq"),
                            ("Ci", "Ci"),
                            ("mCi", "mCi"),
                            ("uCi", "µCi"),
                        ],
                        default="Bq",
                        max_length=10,
                    ),
                ),
                ("Activity_reference_date", models.DateField(blank=True, null=True)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("Dose_rate_surface_uSv", models.FloatField(blank=True, null=True)),
                ("Dose_rate_1m_uSv", models.FloatField(blank=True, null=True)),
                ("Dose_rate_measurement_date", models.DateField(blank=True, null=True)),
                (
                    "source_state",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("Contaminated", "Contaminated")],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("contamination_bq_cm2", models.FloatField(blank=True, null=True)),
                (
                    "Source_Physical_Form",
                    models.CharField(
                        blank=True,
                        choices=[("Solid", "Solid"), ("Liquid", "Liquid")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "Source_Model",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "Source_Practice",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "Device_Manufacturer",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "Device_Model",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "Device_Serial_Number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "Container_Type",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "Transfer_Facility",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("Parent", models.CharField(blank=True, max_length=12, null=True)),
                ("Child", models.CharField(blank=True, max_length=12, null=True)),
                ("Dimension", models.CharField(blank=True, max_length=20)),
                (
                    "Attachments",
                    models.ImageField(blank=True, null=True, upload_to="DSRS_Doc/"),
                ),
                ("Comment", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("initial_activity_bq", models.FloatField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "Nuclide",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.nuclides",
                    ),
                ),
            ],
        ),
    ]
