# Generated by Django 6.0.5 on 2026-06-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dsrs",
            name="Status",
            field=models.CharField(
                choices=[
                    ("Stored", "Stored"),
                    ("Transferred", "Transferred"),
                    ("Loaned", "Loaned"),
                ],
                max_length=15,
            ),
        ),
    ]
