# Generated by Django 6.0.6 on 2026-07-26 10:55

import common.utils.fileValidator
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0002_initial"),
        ("dashboard", "0001_initial"),
        ("facilities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sourcemovement",
            options={"ordering": ["movement_date", "id"]},
        ),
        migrations.RenameField(
            model_name="sourcemovement",
            old_name="quantity",
            new_name="source_count",
        ),
        migrations.RemoveField(
            model_name="dsrs",
            name="Origin_Facility",
        ),
        migrations.RemoveField(
            model_name="historicaldsrs",
            name="Origin_Facility",
        ),
        migrations.AddField(
            model_name="sourcemovement",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="source_movements/",
                validators=[common.utils.fileValidator.validate_attachment],
            ),
        ),
        migrations.AddField(
            model_name="sourcemovement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sourcemovement",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Purchased", "Purchased"),
                    ("In Use", "In Use"),
                    ("Stored", "Stored"),
                    ("Reused", "Reused"),
                    ("Recycled", "Recycled"),
                    ("Disposed", "Disposed"),
                    ("Loaned", "Loaned"),
                    ("Quality control", "Quality control"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Purchased", "Purchased"),
                    ("In Use", "In Use"),
                    ("Stored", "Stored"),
                    ("Reused", "Reused"),
                    ("Recycled", "Recycled"),
                    ("Disposed", "Disposed"),
                    ("Loaned", "Loaned"),
                    ("Quality control", "Quality control"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sourcemovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE", "Purchase"),
                    ("RECEIVE", "Receive"),
                    ("ISSUE", "Issue"),
                    ("RETURN", "Return"),
                    ("TRANSFER", "Transfer"),
                    ("SPLIT", "Split"),
                    ("MERGE", "Merge"),
                    ("REUSE", "Reuse"),
                    ("RECYCLE", "Recycle"),
                    ("DISPOSAL", "Disposal"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sourcemovement",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                to="dashboard.dsrs",
            ),
        ),
        migrations.AddIndex(
            model_name="sourcemovement",
            index=models.Index(
                fields=["source"], name="dashboard_s_source__c47282_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sourcemovement",
            index=models.Index(
                fields=["movement_date"], name="dashboard_s_movemen_4953fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sourcemovement",
            index=models.Index(
                fields=["movement_type"], name="dashboard_s_movemen_d31b47_idx"
            ),
        ),
    ]
