# Generated by Django 6.0.6 on 2026-07-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_sourcemovement_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcemovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE", "Purchase"),
                    ("RECEIVE", "Receive"),
                    ("ISSUE", "Issue"),
                    ("RETURN", "Return"),
                    ("TRANSFER", "Transfer"),
                    ("SPLIT", "Split"),
                    ("MERGE", "Merge"),
                    ("REUSE", "Reuse"),
                    ("RECYCLE", "Recycle"),
                    ("DISPOSAL", "Disposal"),
                    ("LOAN", "Loan"),
                    ("QUALITY_CONTROL", "Quality Control"),
                ],
                max_length=20,
            ),
        ),
    ]
