# Generated by Django 6.0.5 on 2026-06-03 10:05

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_dsrs_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDSRS",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("Irwa_Code", models.CharField(max_length=15)),
                ("Sso_Code", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "Facility",
                    models.CharField(
                        choices=[
                            ("IRWA", "Tehran Site"),
                            ("KJ", "Karaj Site"),
                            ("AK", "Anarak Site"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "Origin_Type",
                    models.CharField(
                        choices=[
                            ("Received", "Received"),
                            ("Historical", "Historical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("Date_received", models.DateField()),
                ("Origin_Facility", models.CharField(max_length=250)),
                ("Location", models.CharField(max_length=20)),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("Stored", "Stored"),
                            ("Transferred", "Transferred"),
                            ("Loaned", "Loaned"),
                        ],
                        max_length=15,
                    ),
                ),
                ("Status_Date", models.DateField()),
                (
                    "Responsible_Person",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("activity_input", models.FloatField(blank=True, null=True)),
                (
                    "activity_unit",
                    models.CharField(
                        choices=[
                            ("Bq", "Bq"),
                            ("kBq", "kBq"),
                            ("MBq", "MBq"),
                            ("GBq", "GBq"),
                            ("Ci", "Ci"),
                            ("mCi", "mCi"),
                            ("uCi", "µCi"),
                        ],
                        default="Bq",
                        max_length=10,
                    ),
                ),
                ("Activity_reference_date", models.DateField(blank=True, null=True)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("Dose_rate_surface_uSv", models.FloatField(blank=True, null=True)),
                ("Dose_rate_1m_uSv", models.FloatField(blank=True, null=True)),
                ("Dose_rate_measurement_date", models.DateField(blank=True, null=True)),
                (
                    "source_state",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("Contaminated", "Contaminated")],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("contamination_bq_cm2", models.FloatField(blank=True, null=True)),
                (
                    "Source_Physical_Form",
                    models.CharField(
                        blank=True,
                        choices=[("Solid", "Solid"), ("Liquid", "Liquid")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "Source_Model",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "Source_Practice",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "Device_Manufacturer",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "Device_Model",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "Device_Serial_Number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "Container_Type",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
               
                ("Parent", models.CharField(blank=True, max_length=12, null=True)),
                ("Child", models.CharField(blank=True, max_length=12, null=True)),
                ("Dimension", models.CharField(blank=True, max_length=20)),
                (
                    "Attachments",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("Comment", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("initial_activity_bq", models.FloatField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "Nuclide",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dashboard.nuclides",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical dsrs",
                "verbose_name_plural": "historical dsrss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
