# Generated by Django 6.0.5 on 2026-06-03 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_historicaldsrs"),
    ]

    operations = [
        migrations.CreateModel(
            name="DSRSImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="dsrs_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dsrs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dsrs_images",
                        to="dashboard.dsrs",
                    ),
                ),
            ],
        ),
    ]
