# Generated by Django 6.0.6 on 2026-07-27 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_sourcemovement_movement_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dsrs",
            name="Attachments",
        ),
        migrations.RemoveField(
            model_name="historicaldsrs",
            name="Attachments",
        ),
    ]
