# Generated by Django 6.0.5 on 2026-06-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_dsrsimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HideShowFilter",
        ),
    ]
