# Generated by Django 6.0.6 on 2026-07-27 05:36

import common.utils.fileValidator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_remove_dsrs_attachments_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sourcemovement",
            name="attachment",
        ),
        migrations.CreateModel(
            name="MovementAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="source_movements/",
                        validators=[common.utils.fileValidator.validate_attachment],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="dashboard.sourcemovement",
                    ),
                ),
            ],
        ),
    ]
