# Generated by Django 6.0.5 on 2026-06-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_delete_hideshowfilter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dsrs",
            name="Transfer_Facility",
        ),
        migrations.AddField(
            model_name="dsrs",
            name="Source_Manufacturer",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="dsrs",
            name="Source_Type",
            field=models.CharField(
                choices=[("SRS", "SRS"), ("DSRS", "DSRS")],
                default="DSRS",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="historicaldsrs",
            name="Source_Manufacturer",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="historicaldsrs",
            name="Source_Type",
            field=models.CharField(
                choices=[("SRS", "SRS"), ("DSRS", "DSRS")],
                default="DSRS",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Facility",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Status",
            field=models.CharField(
                choices=[
                    ("Purchased", "Purchased"),
                    ("In Use", "In Use"),
                    ("Stored", "Stored"),
                    ("Reused", "Reused"),
                    ("Disposed", "Disposed"),
                    ("Loaned", "Loaned"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Facility",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Status",
            field=models.CharField(
                choices=[
                    ("Purchased", "Purchased"),
                    ("In Use", "In Use"),
                    ("Stored", "Stored"),
                    ("Reused", "Reused"),
                    ("Disposed", "Disposed"),
                    ("Loaned", "Loaned"),
                ],
                max_length=15,
            ),
        ),
    ]
