# Generated by Django 6.0.6 on 2026-07-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_remove_sourcemovement_attachment_movementattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dsrs",
            name="Location",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Location",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
