# Generated by Django 6.0.5 on 2026-06-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_remove_dsrs_transfer_facility_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dsrs",
            name="Irwa_Code",
        ),
        migrations.RemoveField(
            model_name="historicaldsrs",
            name="Irwa_Code",
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Date_received",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Origin_Facility",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Origin_Type",
            field=models.CharField(
                choices=[
                    ("Received", "Received"),
                    ("Historical", "Historical"),
                    ("SRS", "SRS"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Date_received",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Origin_Facility",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Origin_Type",
            field=models.CharField(
                choices=[
                    ("Received", "Received"),
                    ("Historical", "Historical"),
                    ("SRS", "SRS"),
                ],
                max_length=20,
            ),
        ),
    ]
