# Generated by Django 6.0.6 on 2026-07-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_dsrs_location_alter_historicaldsrs_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dsrs",
            name="Origin_Type",
            field=models.CharField(
                blank=True,
                choices=[("Received", "Received"), ("Historical", "Historical")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Source_Type",
            field=models.CharField(
                choices=[("NEW", "NEW"), ("DSRS", "DSRS")],
                default="DSRS",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Origin_Type",
            field=models.CharField(
                blank=True,
                choices=[("Received", "Received"), ("Historical", "Historical")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Source_Type",
            field=models.CharField(
                choices=[("NEW", "NEW"), ("DSRS", "DSRS")],
                default="DSRS",
                max_length=10,
            ),
        ),
    ]
