# Generated by Django 6.0.5 on 2026-06-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_remove_dsrs_irwa_code_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ModelFilter",
        ),
    ]
