# Generated by Django 6.0.6 on 2026-08-05 10:30

import common.utils.fileValidator
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0005_alter_contract_created_at_and_more"),
        ("dashboard", "0007_alter_dsrs_origin_type_alter_dsrs_source_type_and_more"),
        ("facilities", "0002_alter_facilitymodel_created_at_and_more"),
        ("reference", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dsrs",
            options={
                "verbose_name": "DSRS Source",
                "verbose_name_plural": "DSRS Sources",
            },
        ),
        migrations.AlterModelOptions(
            name="hideshowfiltert",
            options={
                "verbose_name": "Hide/Show Filter",
                "verbose_name_plural": "Hide/Show Filters",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldsrs",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical DSRS Source",
                "verbose_name_plural": "historical DSRS Sources",
            },
        ),
        migrations.AlterModelOptions(
            name="modelfiltert",
            options={
                "verbose_name": "Model Filter",
                "verbose_name_plural": "Model Filters",
            },
        ),
        migrations.AlterModelOptions(
            name="movementattachment",
            options={
                "verbose_name": "Movement Attachment",
                "verbose_name_plural": "Movement Attachments",
            },
        ),
        migrations.AlterModelOptions(
            name="sourcemovement",
            options={
                "ordering": ["movement_date", "id"],
                "verbose_name": "Source Movement",
                "verbose_name_plural": "Source Movements",
            },
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Activity_reference_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Activity reference date"
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Comment",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Comment"
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Container_Type",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Container Type"
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Date_received",
            field=models.DateField(blank=True, null=True, verbose_name="Date Received"),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Device_Manufacturer",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Device Manufacturer"
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Device_Model",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Device Model"
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Device_Serial_Number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Device Serial Number",
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Dimension",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Dimension"
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Dose_rate_1m_uSv",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Dose rate at 1 m distance uSv"
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Dose_rate_measurement_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Dose rate measurement date"
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Dose_rate_surface_uSv",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Dose rate on surface uSv"
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Location",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Nuclide",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reference.nuclides",
                verbose_name="Nuclide",
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Origin_Type",
            field=models.CharField(
                blank=True,
                choices=[("Received", "Received"), ("Historical", "Historical")],
                max_length=20,
                null=True,
                verbose_name="Origin Type",
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Responsible_Person",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Responsible Person"
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Source_Manufacturer",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Source Manufacturer"
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Source_Model",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Source Model"
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Source_Physical_Form",
            field=models.CharField(
                blank=True,
                choices=[("Solid", "Solid"), ("Liquid", "Liquid")],
                max_length=10,
                null=True,
                verbose_name="Source Physical Form",
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Source_Practice",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Source Practice"
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Source_Type",
            field=models.CharField(
                choices=[("NEW", "NEW"), ("DSRS", "DSRS")],
                default="DSRS",
                max_length=10,
                verbose_name="Source Type",
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Sso_Code",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="SSO Code"
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Purchased", "Purchased"),
                    ("In Use", "In Use"),
                    ("Stored", "Stored"),
                    ("Reused", "Reused"),
                    ("Recycled", "Recycled"),
                    ("Disposed", "Disposed"),
                    ("Loaned", "Loaned"),
                    ("Quality Control", "Quality Control"),
                ],
                max_length=15,
                null=True,
                verbose_name="SOURCE STATUS",
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Status_Date",
            field=models.DateField(blank=True, null=True, verbose_name="Status Date"),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="activity_input",
            field=models.FloatField(
                blank=True, null=True, verbose_name="activityinput"
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="activity_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bq", "Bq"),
                    ("KBq", "KBq"),
                    ("MBq", "MBq"),
                    ("GBq", "GBq"),
                    ("Ci", "Ci"),
                    ("mCi", "mCi"),
                    ("uCi", "uCi"),
                    ("nCi", "nCi"),
                ],
                default="Bq",
                max_length=10,
                null=True,
                verbose_name="activity unit",
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="available_count",
            field=models.PositiveIntegerField(
                default=1, verbose_name="available count"
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="contamination_bq_cm2",
            field=models.FloatField(
                blank=True, null=True, verbose_name="contamination bq/cm2"
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="is_divisible",
            field=models.BooleanField(default=False, verbose_name="is divisible"),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="serial_number",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="serial number"
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="source_count",
            field=models.PositiveIntegerField(default=1, verbose_name="source count"),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="source_state",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("Contaminated", "Contaminated")],
                max_length=15,
                null=True,
                verbose_name="source state",
            ),
        ),
        migrations.AlterField(
            model_name="hideshowfiltert",
            name="key",
            field=models.CharField(max_length=50, verbose_name="Key"),
        ),
        migrations.AlterField(
            model_name="hideshowfiltert",
            name="parent",
            field=models.CharField(max_length=50, verbose_name="Parent"),
        ),
        migrations.AlterField(
            model_name="hideshowfiltert",
            name="value",
            field=models.BooleanField(default=True, verbose_name="Visible"),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Activity_reference_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Activity reference date"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Comment",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Comment"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Container_Type",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Container Type"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Date_received",
            field=models.DateField(blank=True, null=True, verbose_name="Date Received"),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Device_Manufacturer",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Device Manufacturer"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Device_Model",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Device Model"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Device_Serial_Number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Device Serial Number",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Dimension",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Dimension"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Dose_rate_1m_uSv",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Dose rate at 1 m distance uSv"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Dose_rate_measurement_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Dose rate measurement date"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Dose_rate_surface_uSv",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Dose rate on surface uSv"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Location",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Nuclide",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="reference.nuclides",
                verbose_name="Nuclide",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Origin_Type",
            field=models.CharField(
                blank=True,
                choices=[("Received", "Received"), ("Historical", "Historical")],
                max_length=20,
                null=True,
                verbose_name="Origin Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Responsible_Person",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Responsible Person"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Source_Manufacturer",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Source Manufacturer"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Source_Model",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Source Model"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Source_Physical_Form",
            field=models.CharField(
                blank=True,
                choices=[("Solid", "Solid"), ("Liquid", "Liquid")],
                max_length=10,
                null=True,
                verbose_name="Source Physical Form",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Source_Practice",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Source Practice"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Source_Type",
            field=models.CharField(
                choices=[("NEW", "NEW"), ("DSRS", "DSRS")],
                default="DSRS",
                max_length=10,
                verbose_name="Source Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Sso_Code",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="SSO Code"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Purchased", "Purchased"),
                    ("In Use", "In Use"),
                    ("Stored", "Stored"),
                    ("Reused", "Reused"),
                    ("Recycled", "Recycled"),
                    ("Disposed", "Disposed"),
                    ("Loaned", "Loaned"),
                    ("Quality Control", "Quality Control"),
                ],
                max_length=15,
                null=True,
                verbose_name="SOURCE STATUS",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Status_Date",
            field=models.DateField(blank=True, null=True, verbose_name="Status Date"),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="activity_input",
            field=models.FloatField(
                blank=True, null=True, verbose_name="activityinput"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="activity_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bq", "Bq"),
                    ("KBq", "KBq"),
                    ("MBq", "MBq"),
                    ("GBq", "GBq"),
                    ("Ci", "Ci"),
                    ("mCi", "mCi"),
                    ("uCi", "uCi"),
                    ("nCi", "nCi"),
                ],
                default="Bq",
                max_length=10,
                null=True,
                verbose_name="activity unit",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="available_count",
            field=models.PositiveIntegerField(
                default=1, verbose_name="available count"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="contamination_bq_cm2",
            field=models.FloatField(
                blank=True, null=True, verbose_name="contamination bq/cm2"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="is_divisible",
            field=models.BooleanField(default=False, verbose_name="is divisible"),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="serial_number",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="serial number"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="source_count",
            field=models.PositiveIntegerField(default=1, verbose_name="source count"),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="source_state",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("Contaminated", "Contaminated")],
                max_length=15,
                null=True,
                verbose_name="source state",
            ),
        ),
        migrations.AlterField(
            model_name="modelfiltert",
            name="key",
            field=models.CharField(max_length=50, verbose_name="Key"),
        ),
        migrations.AlterField(
            model_name="modelfiltert",
            name="parent",
            field=models.CharField(max_length=50, verbose_name="Parent"),
        ),
        migrations.AlterField(
            model_name="modelfiltert",
            name="value",
            field=models.CharField(max_length=100, verbose_name="Value"),
        ),
        migrations.AlterField(
            model_name="movementattachment",
            name="file",
            field=models.FileField(
                upload_to="source_movements/",
                validators=[common.utils.fileValidator.validate_attachment],
                verbose_name="Attachment File",
            ),
        ),
        migrations.AlterField(
            model_name="movementattachment",
            name="movement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="dashboard.sourcemovement",
                verbose_name="Movement",
            ),
        ),
        migrations.AlterField(
            model_name="movementattachment",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
        ),
        migrations.AlterField(
            model_name="sourcemovement",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contract.licensecontract",
                verbose_name="Contract",
            ),
        ),
        migrations.AlterField(
            model_name="sourcemovement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="sourcemovement",
            name="from_facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="facilities.facilitymodel",
                verbose_name="From Facility",
            ),
        ),
        migrations.AlterField(
            model_name="sourcemovement",
            name="movement_date",
            field=models.DateField(verbose_name="Movement Date"),
        ),
        migrations.AlterField(
            model_name="sourcemovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE", "Purchase"),
                    ("RECEIVE", "Receive"),
                    ("ISSUE", "Issue"),
                    ("RETURN", "Return"),
                    ("TRANSFER", "Transfer"),
                    ("SPLIT", "Split"),
                    ("MERGE", "Merge"),
                    ("REUSE", "Reuse"),
                    ("RECYCLE", "Recycle"),
                    ("DISPOSAL", "Disposal"),
                    ("LOAN", "Loan"),
                    ("QUALITY_CONTROL", "Quality Control"),
                ],
                max_length=20,
                verbose_name="Movement Type",
            ),
        ),
        migrations.AlterField(
            model_name="sourcemovement",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Performed By",
            ),
        ),
        migrations.AlterField(
            model_name="sourcemovement",
            name="remarks",
            field=models.TextField(blank=True, verbose_name="Remarks"),
        ),
        migrations.AlterField(
            model_name="sourcemovement",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                to="dashboard.dsrs",
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="sourcemovement",
            name="source_count",
            field=models.PositiveIntegerField(default=1, verbose_name="Source Count"),
        ),
        migrations.AlterField(
            model_name="sourcemovement",
            name="to_facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="facilities.facilitymodel",
                verbose_name="To Facility",
            ),
        ),
    ]
