# Generated by Django 6.0.5 on 2026-06-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_delete_modelfilter"),
    ]

    operations = [
        migrations.CreateModel(
            name="HideShowFilterT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent", models.CharField(max_length=50)),
                ("key", models.CharField(max_length=50)),
                ("value", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModelFilterT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent", models.CharField(max_length=50)),
                ("key", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="dsrs",
            name="create_contract",
            field=models.BooleanField(default=False, verbose_name="Create Contract"),
        ),
        migrations.AddField(
            model_name="historicaldsrs",
            name="create_contract",
            field=models.BooleanField(default=False, verbose_name="Create Contract"),
        ),
    ]
