# Generated by Django 6.0.5 on 2026-06-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0009_hideshowfiltert_modelfiltert_dsrs_create_contract_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dsrs",
            name="create_contract",
        ),
        migrations.RemoveField(
            model_name="historicaldsrs",
            name="create_contract",
        ),
    ]
