# Generated by Django 6.0.5 on 2026-06-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_remove_dsrs_create_contract_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dsrs",
            name="Child",
        ),
        migrations.RemoveField(
            model_name="dsrs",
            name="Parent",
        ),
        migrations.RemoveField(
            model_name="historicaldsrs",
            name="Child",
        ),
        migrations.RemoveField(
            model_name="historicaldsrs",
            name="Parent",
        ),
    ]
