# Generated by Django 6.0.6 on 2026-06-27 06:02

import waste.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_remove_dsrs_child_remove_dsrs_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dsrs",
            name="DSRSImage",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="dsrs_images/",
                validators=[waste.models.validate_attachment],
            ),
        ),
        migrations.AddField(
            model_name="historicaldsrs",
            name="DSRSImage",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[waste.models.validate_attachment],
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Attachments",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="DSRS_Doc/",
                validators=[waste.models.validate_attachment],
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Attachments",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[waste.models.validate_attachment],
            ),
        ),
        migrations.DeleteModel(
            name="DSRSImage",
        ),
    ]
