# Generated by Django 6.0.6 on 2026-06-27 07:05

import django.db.models.deletion
import waste.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_dsrs_dsrsimage_historicaldsrs_dsrsimage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dsrs",
            name="DSRSImage",
        ),
        migrations.RemoveField(
            model_name="historicaldsrs",
            name="DSRSImage",
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Attachments",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="dsrs_images/",
                validators=[waste.models.validate_attachment],
            ),
        ),
        migrations.CreateModel(
            name="DSRSImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="dsrs_images/",
                        validators=[waste.models.validate_attachment],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dsrs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dsrs_images",
                        to="dashboard.dsrs",
                    ),
                ),
            ],
        ),
    ]
