# Generated by Django 6.0.6 on 2026-07-11 11:35

import waste.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_remove_dsrs_dsrsimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dsrs",
            name="Attachments",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="DSRS_Doc",
                validators=[waste.models.validate_attachment],
            ),
        ),
    ]
