# Generated by Django 6.0.6 on 2026-07-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_alter_dsrs_attachments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dsrs",
            name="Dimension",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Location",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Purchased", "Purchased"),
                    ("In Use", "In Use"),
                    ("Stored", "Stored"),
                    ("Reused", "Reused"),
                    ("Disposed", "Disposed"),
                    ("Loaned", "Loaned"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Status_Date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="activity_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bq", "Bq"),
                    ("kBq", "kBq"),
                    ("MBq", "MBq"),
                    ("GBq", "GBq"),
                    ("Ci", "Ci"),
                    ("mCi", "mCi"),
                    ("uCi", "µCi"),
                ],
                default="Bq",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Dimension",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Location",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Purchased", "Purchased"),
                    ("In Use", "In Use"),
                    ("Stored", "Stored"),
                    ("Reused", "Reused"),
                    ("Disposed", "Disposed"),
                    ("Loaned", "Loaned"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Status_Date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="activity_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bq", "Bq"),
                    ("kBq", "kBq"),
                    ("MBq", "MBq"),
                    ("GBq", "GBq"),
                    ("Ci", "Ci"),
                    ("mCi", "mCi"),
                    ("uCi", "µCi"),
                ],
                default="Bq",
                max_length=10,
                null=True,
            ),
        ),
    ]
