# Generated by Django 6.0.6 on 2026-07-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_alter_dsrs_dimension_alter_dsrs_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dsrs",
            name="Origin_Type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Received", "Received"),
                    ("Historical", "Historical"),
                    ("SRS", "SRS"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Origin_Type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Received", "Received"),
                    ("Historical", "Historical"),
                    ("SRS", "SRS"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
