# Generated by Django 6.0.6 on 2026-07-17 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_alter_dsrs_origin_type_and_more"),
        ("laboratory", "0004_alter_gammaactivity_radionuclide"),
        ("reference", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dsrs",
            name="Nuclide",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reference.nuclides",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Nuclide",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="reference.nuclides",
            ),
        ),
        migrations.DeleteModel(
            name="Nuclides",
        ),
    ]
