# Generated by Django 6.0.6 on 2026-07-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_alter_dsrs_nuclide_alter_historicaldsrs_nuclide_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dsrs",
            name="Source_Type",
            field=models.CharField(
                choices=[("Solid", "Solid"), ("Liquid", "Liquid")],
                default="DSRS",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="activity_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bq", "Bq"),
                    ("kBq", "kBq"),
                    ("MBq", "MBq"),
                    ("GBq", "GBq"),
                    ("Ci", "Ci"),
                    ("mCi", "mCi"),
                    ("µCi", "µCi"),
                ],
                default="Bq",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Source_Type",
            field=models.CharField(
                choices=[("Solid", "Solid"), ("Liquid", "Liquid")],
                default="DSRS",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="activity_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bq", "Bq"),
                    ("kBq", "kBq"),
                    ("MBq", "MBq"),
                    ("GBq", "GBq"),
                    ("Ci", "Ci"),
                    ("mCi", "mCi"),
                    ("µCi", "µCi"),
                ],
                default="Bq",
                max_length=10,
                null=True,
            ),
        ),
    ]
