# Generated by Django 6.0.6 on 2026-07-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_alter_dsrs_source_type_alter_dsrs_activity_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dsrs",
            name="activity_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bq", "Becquerel"),
                    ("KBq", "Kilobecquerel"),
                    ("MBq", "Megabecquerel"),
                    ("GBq", "Gigabecquerel"),
                    ("Ci", "Curie"),
                    ("mCi", "Millicurie"),
                    ("uCi", "Microcurie"),
                    ("nCi", "Nanocurie"),
                ],
                default="Bq",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="activity_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bq", "Becquerel"),
                    ("KBq", "Kilobecquerel"),
                    ("MBq", "Megabecquerel"),
                    ("GBq", "Gigabecquerel"),
                    ("Ci", "Curie"),
                    ("mCi", "Millicurie"),
                    ("uCi", "Microcurie"),
                    ("nCi", "Nanocurie"),
                ],
                default="Bq",
                max_length=10,
                null=True,
            ),
        ),
    ]
