# Generated by Django 6.0.6 on 2026-07-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0019_alter_dsrs_activity_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dsrs",
            name="Status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Purchased", "Purchased"),
                    ("In Use", "In Use"),
                    ("Stored", "Stored"),
                    ("Reused", "Reused"),
                    ("Recycled", "Recycled"),
                    ("Disposed", "Disposed"),
                    ("Loaned", "Loaned"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Purchased", "Purchased"),
                    ("In Use", "In Use"),
                    ("Stored", "Stored"),
                    ("Reused", "Reused"),
                    ("Recycled", "Recycled"),
                    ("Disposed", "Disposed"),
                    ("Loaned", "Loaned"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
