# Generated by Django 6.0.6 on 2026-07-25 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0004_alter_licensecontract_contract_accountable_and_more"),
        ("dashboard", "0020_alter_dsrs_status_alter_historicaldsrs_status"),
        ("facilities", "0003_remove_facility_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="dsrs",
            name="available_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="dsrs",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contract.licensecontract",
            ),
        ),
        migrations.AddField(
            model_name="dsrs",
            name="created_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="dashboard.dsrs",
            ),
        ),
        migrations.AddField(
            model_name="dsrs",
            name="is_divisible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dsrs",
            name="source_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="historicaldsrs",
            name="available_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="historicaldsrs",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contract.licensecontract",
            ),
        ),
        migrations.AddField(
            model_name="historicaldsrs",
            name="created_from",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dashboard.dsrs",
            ),
        ),
        migrations.AddField(
            model_name="historicaldsrs",
            name="is_divisible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaldsrs",
            name="source_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="Source_Type",
            field=models.CharField(
                choices=[("SRS", "SRS"), ("DSRS", "DSRS")],
                default="DSRS",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="dsrs",
            name="activity_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bq", "Bq"),
                    ("KBq", "KBq"),
                    ("MBq", "MBq"),
                    ("GBq", "GBq"),
                    ("Ci", "Ci"),
                    ("mCi", "mCi"),
                    ("uCi", "uCi"),
                    ("nCi", "nCi"),
                ],
                default="Bq",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="Source_Type",
            field=models.CharField(
                choices=[("SRS", "SRS"), ("DSRS", "DSRS")],
                default="DSRS",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldsrs",
            name="activity_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bq", "Bq"),
                    ("KBq", "KBq"),
                    ("MBq", "MBq"),
                    ("GBq", "GBq"),
                    ("Ci", "Ci"),
                    ("mCi", "mCi"),
                    ("uCi", "uCi"),
                    ("nCi", "nCi"),
                ],
                default="Bq",
                max_length=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="SourceMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("ISSUE", "Issue"),
                            ("RETURN", "Return"),
                            ("REUSE", "Reuse"),
                            ("RECYCLE", "Recycle"),
                            ("DISPOSAL", "Disposal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("movement_date", models.DateField()),
                ("remarks", models.TextField(blank=True)),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contract.licensecontract",
                    ),
                ),
                (
                    "from_facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="facilities.facility",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dashboard.dsrs"
                    ),
                ),
                (
                    "to_facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="facilities.facility",
                    ),
                ),
            ],
        ),
    ]
