# Generated by Django 6.0.6 on 2026-08-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "view_name",
                    models.CharField(
                        help_text="The Django URL name (the 'name=' in urls.py), e.g. 'add_source'.",
                        max_length=150,
                        unique=True,
                        verbose_name="View Name",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        help_text="User needs to belong to AT LEAST ONE of these groups.",
                        related_name="view_permissions",
                        to="auth.group",
                        verbose_name="Allowed Groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "View Permission",
                "verbose_name_plural": "View Permissions",
                "ordering": ["view_name"],
            },
        ),
    ]
