# Generated by Django 6.0.6 on 2026-07-20 12:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="position",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="signature_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload transparent PNG, recommended 800x300 px",
                null=True,
                upload_to=accounts.models.signature_upload_path,
            ),
        ),
    ]
