# Generated by Django 6.0.6 on 2026-09-21 04:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_viewpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signature_clean',
            field=models.ImageField(blank=True, editable=False, help_text='Automatically generated transparent signature', null=True, upload_to=accounts.models.clean_signature_upload_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Upload scanned signature image', null=True, upload_to=accounts.models.signature_upload_path),
        ),
    ]
