# Generated by Django 6.0.6 on 2026-06-17 05:51

import django.db.models.deletion
import waste.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WasteBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("waste_id", models.CharField(max_length=100, unique=True)),
                (
                    "waste_type",
                    models.CharField(
                        choices=[("LIQUID", "Liquid"), ("SOLID", "Solid")],
                        max_length=10,
                    ),
                ),
                (
                    "waste_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VLLW", "Very Low Level Waste"),
                            ("LLW", "Low Level Waste"),
                            ("ILW", "Intermediate Level Waste"),
                            ("HLW", "High Level Waste"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "waste_state",
                    models.CharField(
                        choices=[
                            ("UNPROCESSED", "Unprocessed"),
                            ("PROCESSED", "Processed"),
                            ("CONDITIONED", "Conditioned"),
                        ],
                        default="UNPROCESSED",
                        max_length=20,
                    ),
                ),
                (
                    "facility",
                    models.CharField(
                        choices=[
                            ("TEHRAN", "Tehran"),
                            ("KARAJ", "Karaj"),
                            ("ANARAK", "Anarak"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "origin_of_waste",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("HISTORICAL", "Historical"),
                            ("GENERATED", "Generated by Home Facility"),
                            ("PROCESSING", "Generated by Processing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_received", models.DateField()),
                (
                    "origin_facility",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("material", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "container_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mass_kg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "volume_m3",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "dose_rate_1m",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "dose_rate_surface",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "alpha_contamination",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "beta_gamma_contamination",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RELEASED", "Released"),
                            ("CONSUMED", "Consumed"),
                            ("STORED", "Stored"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="attachments/",
                        validators=[waste.models.validate_attachment],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LiquidWasteDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ph",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "density",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "total_solids",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "suspended_solids",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "soluble_solids",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "possible_treatment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CHEMICAL", "Chemical Treatment"),
                            ("SEDIMENTATION", "Sedimentation"),
                            ("FILTRATION", "Filtration"),
                            ("CEMENTATION", "Cementation"),
                            ("INCINERATION", "Incineration"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquid_details",
                        to="waste.wastebatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WasteConditioning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pretreatment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CHEMICAL", "Chemical Treatment"),
                            ("SEDIMENTATION", "Sedimentation"),
                            ("FILTRATION", "Filtration"),
                            ("CEMENTATION", "Cementation"),
                            ("INCINERATION", "Incineration"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "treatment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CHEMICAL", "Chemical Treatment"),
                            ("SEDIMENTATION", "Sedimentation"),
                            ("FILTRATION", "Filtration"),
                            ("CEMENTATION", "Cementation"),
                            ("INCINERATION", "Incineration"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "further_conditioning_planned",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "conditioning_matrix",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "waste_to_matrix_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditioning",
                        to="waste.wastebatch",
                    ),
                ),
            ],
        ),
    ]
