# Generated by Django 6.0.6 on 2026-06-17 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0002_analysis_analysis_notes_analysis_is_latest_and_more"),
        ("waste", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wastebatch",
            name="current_alpha_bq",
            field=models.DecimalField(
                blank=True, decimal_places=5, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="wastebatch",
            name="current_beta_bq",
            field=models.DecimalField(
                blank=True, decimal_places=5, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="wastebatch",
            name="current_gamma_bq",
            field=models.DecimalField(
                blank=True, decimal_places=5, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="wastebatch",
            name="current_total_activity_bq",
            field=models.DecimalField(
                blank=True, decimal_places=5, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="wastebatch",
            name="generation_number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wastebatch",
            name="latest_analysis_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wastebatch",
            name="parent_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="BatchActivitySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alpha_bq", models.DecimalField(decimal_places=5, max_digits=20)),
                ("beta_bq", models.DecimalField(decimal_places=5, max_digits=20)),
                ("gamma_bq", models.DecimalField(decimal_places=5, max_digits=20)),
                (
                    "total_activity_bq",
                    models.DecimalField(decimal_places=5, max_digits=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratory.analysis",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_snapshots",
                        to="waste.wastebatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
