# Generated by Django 6.0.6 on 2026-09-20 06:03

import common.utils.fileValidator
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_remove_facilitymodel_unique_facility_name_and_more'),
        ('waste', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidwastedetails',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='wasteconditioning',
            name='batch',
        ),
        migrations.AlterModelOptions(
            name='wastebatch',
            options={'ordering': ('-created_at', 'waste_id'), 'verbose_name': 'Waste Batch', 'verbose_name_plural': 'Waste Batches'},
        ),
        migrations.RemoveField(
            model_name='wastebatch',
            name='alpha_contamination',
        ),
        migrations.RemoveField(
            model_name='wastebatch',
            name='beta_gamma_contamination',
        ),
        migrations.RemoveField(
            model_name='wastebatch',
            name='current_alpha_bq',
        ),
        migrations.RemoveField(
            model_name='wastebatch',
            name='current_beta_bq',
        ),
        migrations.RemoveField(
            model_name='wastebatch',
            name='current_gamma_bq',
        ),
        migrations.RemoveField(
            model_name='wastebatch',
            name='current_total_activity_bq',
        ),
        migrations.RemoveField(
            model_name='wastebatch',
            name='dose_rate_1m',
        ),
        migrations.RemoveField(
            model_name='wastebatch',
            name='dose_rate_surface',
        ),
        migrations.RemoveField(
            model_name='wastebatch',
            name='generation_number',
        ),
        migrations.RemoveField(
            model_name='wastebatch',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='wastebatch',
            name='latest_analysis_date',
        ),
        migrations.RemoveField(
            model_name='wastebatch',
            name='parent_count',
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='alpha_contamination_bq_cm2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='Alpha Contamination (Bq/cm²)'),
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='beta_gamma_contamination_bq_cm2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, verbose_name='Beta/Gamma Contamination (Bq/cm²)'),
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Density'),
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='dose_rate_1m_uSv',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Dose Rate @ 1m (µSv/h)'),
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='dose_rate_date',
            field=models.DateField(blank=True, null=True, verbose_name='Dose Measurement Date'),
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='dose_rate_surface_uSv',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Surface Dose Rate (µSv/h)'),
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='package_mass_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Package Mass (kg)'),
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='package_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Package Type'),
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='package_volume_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Package Volume (m³)'),
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='pH'),
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='possible_pretreatment',
            field=models.CharField(blank=True, choices=[('DISMANTLING', 'Dismantling'), ('SAWING', 'Sawing'), ('CHEMICAL', 'Chemical Adjustment'), ('SHREDDING', 'Shredding'), ('CRUSHING', 'Crushing'), ('SEGREGATION', 'Segregation')], max_length=30, null=True, verbose_name='Possible Pre-Treatment'),
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='possible_treatment',
            field=models.CharField(blank=True, choices=[('CHEMICAL', 'Chemical Precipitation'), ('EVAPORATION', 'Evaporation'), ('ION_EXCHANGE', 'Ion Exchange'), ('COMPACTION', 'Compaction'), ('CONDITIONING', 'Conditioning'), ('SEDIMENTATION', 'Sedimentation'), ('FILTRATION', 'Filtration'), ('CEMENTATION', 'Cementation'), ('REMOVAL', 'Removal'), ('INCINERATION', 'Incineration')], max_length=30, null=True, verbose_name='Possible Treatment'),
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='pretreatment',
            field=models.CharField(blank=True, choices=[('DISMANTLING', 'Dismantling'), ('SAWING', 'Sawing'), ('CHEMICAL', 'Chemical Adjustment'), ('SHREDDING', 'Shredding'), ('CRUSHING', 'Crushing'), ('SEGREGATION', 'Segregation')], max_length=30, null=True, verbose_name='Pre-Treatment Applied'),
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='soluble_solids',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Soluble Solids'),
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='status_date',
            field=models.DateField(blank=True, null=True, verbose_name='Status Date'),
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='suspended_solids',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Suspended Solids'),
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='total_solids',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Total Solids'),
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='treatment',
            field=models.CharField(blank=True, choices=[('CHEMICAL', 'Chemical Precipitation'), ('EVAPORATION', 'Evaporation'), ('ION_EXCHANGE', 'Ion Exchange'), ('COMPACTION', 'Compaction'), ('CONDITIONING', 'Conditioning'), ('SEDIMENTATION', 'Sedimentation'), ('FILTRATION', 'Filtration'), ('CEMENTATION', 'Cementation'), ('REMOVAL', 'Removal'), ('INCINERATION', 'Incineration')], max_length=30, null=True, verbose_name='Treatment Applied'),
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='waste_arising_from',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Waste Arising From'),
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='waste_mass_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Waste Mass (kg)'),
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='waste_matrix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Waste Matrix'),
        ),
        migrations.AddField(
            model_name='wastebatch',
            name='waste_to_matrix_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Waste to Matrix Ratio'),
        ),
        migrations.AlterField(
            model_name='wastebatch',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='waste/attachments/', validators=[common.utils.fileValidator.validate_attachment], verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='wastebatch',
            name='container_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Container Type'),
        ),
        migrations.AlterField(
            model_name='wastebatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='wastebatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='wastebatch',
            name='date_received',
            field=models.DateField(blank=True, null=True, verbose_name='Date Received'),
        ),
        migrations.AlterField(
            model_name='wastebatch',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='wastebatch',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_batches', to='facilities.facilitymodel', verbose_name='Current Facility'),
        ),
        migrations.AlterField(
            model_name='wastebatch',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Storage Location'),
        ),
        migrations.AlterField(
            model_name='wastebatch',
            name='mass_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Mass (kg)'),
        ),
        migrations.AlterField(
            model_name='wastebatch',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='wastebatch',
            name='origin_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_waste_batches', to='facilities.facilitymodel', verbose_name='Origin Facility'),
        ),
        migrations.AlterField(
            model_name='wastebatch',
            name='origin_of_waste',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('HISTORICAL', 'Historical'), ('GENERATED', 'Generated by Home Facility'), ('PROCESSING', 'Generated by Processing')], max_length=20, verbose_name='Origin of Waste'),
        ),
        migrations.AlterField(
            model_name='wastebatch',
            name='status',
            field=models.CharField(choices=[('STORED', 'Stored'), ('IN_TREATMENT', 'In Treatment'), ('TRANSFERRED', 'Transferred'), ('RELEASED', 'Released'), ('DISPOSED', 'Disposed'), ('CONSUMED', 'Consumed (merged/split/conditioned into another batch)')], default='STORED', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='wastebatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='wastebatch',
            name='volume_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Volume (m³)'),
        ),
        migrations.AlterField(
            model_name='wastebatch',
            name='waste_class',
            field=models.CharField(blank=True, choices=[('VLLW', 'Very Low Level Waste'), ('LLW', 'Low Level Waste'), ('ILW', 'Intermediate Level Waste'), ('HLW', 'High Level Waste')], max_length=10, null=True, verbose_name='Waste Class'),
        ),
        migrations.AlterField(
            model_name='wastebatch',
            name='waste_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Waste ID'),
        ),
        migrations.AlterField(
            model_name='wastebatch',
            name='waste_state',
            field=models.CharField(choices=[('UNPROCESSED', 'Unprocessed'), ('PROCESSED', 'Processed')], default='UNPROCESSED', max_length=20, verbose_name='Waste State'),
        ),
        migrations.AlterField(
            model_name='wastebatch',
            name='waste_type',
            field=models.CharField(choices=[('LIQUID', 'Liquid'), ('SOLID', 'Solid')], max_length=10, verbose_name='Waste Type'),
        ),
        migrations.CreateModel(
            name='HistoricalWasteBatch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('waste_id', models.CharField(db_index=True, max_length=100, verbose_name='Waste ID')),
                ('waste_type', models.CharField(choices=[('LIQUID', 'Liquid'), ('SOLID', 'Solid')], max_length=10, verbose_name='Waste Type')),
                ('waste_class', models.CharField(blank=True, choices=[('VLLW', 'Very Low Level Waste'), ('LLW', 'Low Level Waste'), ('ILW', 'Intermediate Level Waste'), ('HLW', 'High Level Waste')], max_length=10, null=True, verbose_name='Waste Class')),
                ('waste_state', models.CharField(choices=[('UNPROCESSED', 'Unprocessed'), ('PROCESSED', 'Processed')], default='UNPROCESSED', max_length=20, verbose_name='Waste State')),
                ('origin_of_waste', models.CharField(choices=[('RECEIVED', 'Received'), ('HISTORICAL', 'Historical'), ('GENERATED', 'Generated by Home Facility'), ('PROCESSING', 'Generated by Processing')], max_length=20, verbose_name='Origin of Waste')),
                ('date_received', models.DateField(blank=True, null=True, verbose_name='Date Received')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('waste_arising_from', models.CharField(blank=True, max_length=100, null=True, verbose_name='Waste Arising From')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Material')),
                ('container_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Container Type')),
                ('mass_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Mass (kg)')),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Volume (m³)')),
                ('dose_rate_surface_uSv', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Surface Dose Rate (µSv/h)')),
                ('dose_rate_1m_uSv', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Dose Rate @ 1m (µSv/h)')),
                ('dose_rate_date', models.DateField(blank=True, null=True, verbose_name='Dose Measurement Date')),
                ('alpha_contamination_bq_cm2', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='Alpha Contamination (Bq/cm²)')),
                ('beta_gamma_contamination_bq_cm2', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, verbose_name='Beta/Gamma Contamination (Bq/cm²)')),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='pH')),
                ('density', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Density')),
                ('total_solids', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Total Solids')),
                ('suspended_solids', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Suspended Solids')),
                ('soluble_solids', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Soluble Solids')),
                ('possible_pretreatment', models.CharField(blank=True, choices=[('DISMANTLING', 'Dismantling'), ('SAWING', 'Sawing'), ('CHEMICAL', 'Chemical Adjustment'), ('SHREDDING', 'Shredding'), ('CRUSHING', 'Crushing'), ('SEGREGATION', 'Segregation')], max_length=30, null=True, verbose_name='Possible Pre-Treatment')),
                ('possible_treatment', models.CharField(blank=True, choices=[('CHEMICAL', 'Chemical Precipitation'), ('EVAPORATION', 'Evaporation'), ('ION_EXCHANGE', 'Ion Exchange'), ('COMPACTION', 'Compaction'), ('CONDITIONING', 'Conditioning'), ('SEDIMENTATION', 'Sedimentation'), ('FILTRATION', 'Filtration'), ('CEMENTATION', 'Cementation'), ('REMOVAL', 'Removal'), ('INCINERATION', 'Incineration')], max_length=30, null=True, verbose_name='Possible Treatment')),
                ('pretreatment', models.CharField(blank=True, choices=[('DISMANTLING', 'Dismantling'), ('SAWING', 'Sawing'), ('CHEMICAL', 'Chemical Adjustment'), ('SHREDDING', 'Shredding'), ('CRUSHING', 'Crushing'), ('SEGREGATION', 'Segregation')], max_length=30, null=True, verbose_name='Pre-Treatment Applied')),
                ('treatment', models.CharField(blank=True, choices=[('CHEMICAL', 'Chemical Precipitation'), ('EVAPORATION', 'Evaporation'), ('ION_EXCHANGE', 'Ion Exchange'), ('COMPACTION', 'Compaction'), ('CONDITIONING', 'Conditioning'), ('SEDIMENTATION', 'Sedimentation'), ('FILTRATION', 'Filtration'), ('CEMENTATION', 'Cementation'), ('REMOVAL', 'Removal'), ('INCINERATION', 'Incineration')], max_length=30, null=True, verbose_name='Treatment Applied')),
                ('package_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Package Type')),
                ('waste_matrix', models.CharField(blank=True, max_length=100, null=True, verbose_name='Waste Matrix')),
                ('waste_to_matrix_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Waste to Matrix Ratio')),
                ('waste_mass_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Waste Mass (kg)')),
                ('package_mass_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Package Mass (kg)')),
                ('package_volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Package Volume (m³)')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Storage Location')),
                ('status', models.CharField(choices=[('STORED', 'Stored'), ('IN_TREATMENT', 'In Treatment'), ('TRANSFERRED', 'Transferred'), ('RELEASED', 'Released'), ('DISPOSED', 'Disposed'), ('CONSUMED', 'Consumed (merged/split/conditioned into another batch)')], default='STORED', max_length=20, verbose_name='Status')),
                ('status_date', models.DateField(blank=True, null=True, verbose_name='Status Date')),
                ('attachment', models.TextField(blank=True, max_length=100, null=True, validators=[common.utils.fileValidator.validate_attachment], verbose_name='Attachment')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated At')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('facility', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='facilities.facilitymodel', verbose_name='Current Facility')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('origin_facility', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='facilities.facilitymodel', verbose_name='Origin Facility')),
            ],
            options={
                'verbose_name': 'historical Waste Batch',
                'verbose_name_plural': 'historical Waste Batches',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WasteBatchLineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('MERGE', 'Merge'), ('SPLIT', 'Split'), ('CONDITIONING', 'Conditioning')], max_length=20, verbose_name='Operation')),
                ('mass_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Mass Contributed (kg)')),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Volume Contributed (m³)')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Performed At')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='waste.wastebatch', verbose_name='Resulting Batch')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_links', to='waste.wastebatch', verbose_name='Parent Batch')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
            ],
            options={
                'verbose_name': 'Waste Batch Lineage',
                'verbose_name_plural': 'Waste Batch Lineage',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='WasteMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RECEIVE', 'Receive'), ('TRANSFER', 'Transfer'), ('STORE', 'Store'), ('TREATMENT', 'Send to Treatment'), ('RELEASE', 'Release'), ('DISPOSAL', 'Disposal'), ('MERGE', 'Merge'), ('SPLIT', 'Split'), ('CONDITIONING', 'Conditioning')], max_length=20, verbose_name='Movement Type')),
                ('movement_date', models.DateField(verbose_name='Movement Date')),
                ('mass_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Mass Moved (kg)')),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Volume Moved (m³)')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='waste.wastebatch', verbose_name='Batch')),
                ('from_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='facilities.facilitymodel', verbose_name='From Facility')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
                ('to_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='facilities.facilitymodel', verbose_name='To Facility')),
            ],
            options={
                'verbose_name': 'Waste Movement',
                'verbose_name_plural': 'Waste Movements',
                'ordering': ['movement_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WasteMovementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='waste/movements/', validators=[common.utils.fileValidator.validate_attachment], verbose_name='Attachment File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='waste.wastemovement', verbose_name='Movement')),
            ],
            options={
                'verbose_name': 'Waste Movement Attachment',
                'verbose_name_plural': 'Waste Movement Attachments',
            },
        ),
        migrations.DeleteModel(
            name='BatchActivitySnapshot',
        ),
        migrations.DeleteModel(
            name='LiquidWasteDetails',
        ),
        migrations.DeleteModel(
            name='WasteConditioning',
        ),
        migrations.AddIndex(
            model_name='wastemovement',
            index=models.Index(fields=['batch'], name='waste_waste_batch_i_84471b_idx'),
        ),
        migrations.AddIndex(
            model_name='wastemovement',
            index=models.Index(fields=['movement_date'], name='waste_waste_movemen_f9c5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='wastemovement',
            index=models.Index(fields=['movement_type'], name='waste_waste_movemen_b2033e_idx'),
        ),
    ]
