# Generated by Django 6.0.6 on 2026-09-28 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0003_remove_facilitymodel_unique_facility_name_and_more"),
        ("waste", "0002_remove_liquidwastedetails_batch_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwastebatch",
            name="waste_appearance",
            field=models.CharField(
                blank=True,
                help_text="Physical appearance: colour, clarity, texture, visible solids…",
                max_length=255,
                null=True,
                verbose_name="Waste Appearance",
            ),
        ),
        migrations.AddField(
            model_name="wastebatch",
            name="waste_appearance",
            field=models.CharField(
                blank=True,
                help_text="Physical appearance: colour, clarity, texture, visible solids…",
                max_length=255,
                null=True,
                verbose_name="Waste Appearance",
            ),
        ),
        migrations.AlterField(
            model_name="historicalwastebatch",
            name="mass_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Total mass of the batch as held (including packaging, if any).",
                max_digits=12,
                null=True,
                verbose_name="Mass (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalwastebatch",
            name="waste_mass_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Mass of the waste itself, without matrix/package.",
                max_digits=12,
                null=True,
                verbose_name="Waste Mass (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="wastebatch",
            name="mass_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Total mass of the batch as held (including packaging, if any).",
                max_digits=12,
                null=True,
                verbose_name="Mass (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="wastebatch",
            name="waste_mass_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Mass of the waste itself, without matrix/package.",
                max_digits=12,
                null=True,
                verbose_name="Waste Mass (kg)",
            ),
        ),
        migrations.AddIndex(
            model_name="wastebatch",
            index=models.Index(fields=["status"], name="waste_waste_status_a6f753_idx"),
        ),
        migrations.AddIndex(
            model_name="wastebatch",
            index=models.Index(
                fields=["facility", "status"], name="waste_waste_facilit_56baab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wastebatch",
            index=models.Index(
                fields=["waste_type", "waste_state"],
                name="waste_waste_waste_t_5cb378_idx",
            ),
        ),
    ]
