# Generated by Django 6.0.6 on 2026-07-15 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("waste", "0002_wastebatch_current_alpha_bq_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wastebatch",
            options={"ordering": ("-created_at", "waste_id")},
        ),
    ]
