# Generated by Django 6.0.6 on 2026-09-29 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0003_remove_facilitymodel_unique_facility_name_and_more"),
        ("reference", "0001_initial"),
        ("waste", "0003_historicalwastebatch_waste_appearance_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditioningIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("WASTE", "Waste / Sludge"),
                            ("CEMENT", "Cement"),
                            ("WATER", "Water"),
                            ("NAOH", "Sodium Hydroxide (NaOH)"),
                            ("MICROSILICA", "Microsilica"),
                            ("PENETRON", "Penetron"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Material",
                    ),
                ),
                (
                    "material_other",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Material (if Other)",
                    ),
                ),
                (
                    "mass_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Mass (kg)",
                    ),
                ),
                (
                    "volume_l",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Volume (L)",
                    ),
                ),
                (
                    "density_kg_per_l",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Used to work out mass from volume, or volume from mass, when only one is measured.",
                        max_digits=8,
                        null=True,
                        verbose_name="Density (kg/L)",
                    ),
                ),
                (
                    "lineage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="waste.wastebatchlineage",
                        verbose_name="Conditioning Operation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conditioning Ingredient",
                "verbose_name_plural": "Conditioning Ingredients",
            },
        ),
        migrations.CreateModel(
            name="ReleaseLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("NUCLIDE", "Specific Radionuclide"),
                            ("GROSS_BETA", "Unidentified Gross Beta"),
                            ("GROSS_ALPHA", "Unidentified Gross Alpha"),
                        ],
                        default="NUCLIDE",
                        max_length=12,
                        verbose_name="Category",
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("LIQUID", "Liquid Discharge"),
                            ("GASEOUS", "Gaseous Discharge"),
                        ],
                        max_length=10,
                        verbose_name="Discharge Route",
                    ),
                ),
                (
                    "annual_limit_bq",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=20,
                        verbose_name="Annual Limit (Bq/year)",
                    ),
                ),
                ("effective_from", models.DateField(verbose_name="Effective From")),
                (
                    "effective_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="Effective To"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Regulatory Reference"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for a limit that applies to every facility.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_limits",
                        to="facilities.facilitymodel",
                        verbose_name="Facility",
                    ),
                ),
                (
                    "radionuclide",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_limits",
                        to="reference.nuclides",
                        verbose_name="Radionuclide",
                    ),
                ),
            ],
            options={
                "verbose_name": "Release Limit",
                "verbose_name_plural": "Release Limits",
                "ordering": ["route", "radionuclide__name"],
            },
        ),
        migrations.CreateModel(
            name="ReleaseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("LIQUID", "Liquid Discharge"),
                            ("GASEOUS", "Gaseous Discharge"),
                        ],
                        max_length=10,
                        verbose_name="Discharge Route",
                    ),
                ),
                ("release_date", models.DateField(verbose_name="Release Date")),
                ("remarks", models.TextField(blank=True, verbose_name="Remarks")),
                (
                    "over_limit",
                    models.BooleanField(
                        default=False, verbose_name="Exceeded an annual limit"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_records",
                        to="waste.wastebatch",
                        verbose_name="Batch",
                    ),
                ),
                (
                    "movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_record",
                        to="waste.wastemovement",
                        verbose_name="Movement",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Performed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Release Record",
                "verbose_name_plural": "Release Records",
                "ordering": ["-release_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ReleaseActivityLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("NUCLIDE", "Specific Radionuclide"),
                            ("GROSS_BETA", "Unidentified Gross Beta"),
                            ("GROSS_ALPHA", "Unidentified Gross Alpha"),
                        ],
                        max_length=12,
                        verbose_name="Category",
                    ),
                ),
                (
                    "activity_bq",
                    models.DecimalField(
                        decimal_places=5, max_digits=20, verbose_name="Activity (Bq)"
                    ),
                ),
                (
                    "radionuclide",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reference.nuclides",
                        verbose_name="Radionuclide",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="waste.releaserecord",
                        verbose_name="Release",
                    ),
                ),
            ],
            options={
                "verbose_name": "Release Activity Line",
                "verbose_name_plural": "Release Activity Lines",
            },
        ),
    ]
