# Generated by Django 6.0.6 on 2026-10-04 10:41

import common.utils.fileValidator
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0003_remove_facilitymodel_unique_facility_name_and_more"),
        ("waste", "0004_conditioningingredient_releaselimit_releaserecord_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WasteIdCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(max_length=20, unique=True)),
                ("last_value", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="historicalwastebatch",
            name="hardness",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Hardness",
            ),
        ),
        migrations.AddField(
            model_name="wastebatch",
            name="hardness",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Hardness",
            ),
        ),
        migrations.AlterField(
            model_name="historicalwastebatch",
            name="material",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LIQUID", "Liquid"),
                    (
                        "LIGHTWEIGHT",
                        "Lightweight Materials (Paper, Cloth, Plastic, etc.)",
                    ),
                    ("HEAVY", "Heavy Materials (Metals, Glass, Syringes, etc.)"),
                    ("FILTERS", "Filters"),
                    ("RESINS", "Resins"),
                    ("BIOLOGICAL", "Biological"),
                    ("CHARCOAL", "Charcoal"),
                    ("OTHER", "Other"),
                    ("SPECIAL_OTHER", "Special Other"),
                    ("SOIL_SEDIMENTS_SLUDGE", "Soil, Sediments and Sludge"),
                ],
                max_length=30,
                null=True,
                verbose_name="Material",
            ),
        ),
        migrations.AlterField(
            model_name="historicalwastebatch",
            name="package_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BAG", "Bag"),
                    ("LARGE_BIN", "Large Bin"),
                    ("BOX", "Box"),
                    ("CONTAINER", "Container"),
                    ("DRUM", "Drum"),
                    ("NON_STANDARD", "Non-standard"),
                    ("CAN", "Can"),
                    ("SMALL_BIN", "Small Bin"),
                    ("SMALL_PIPE", "Small Pipe"),
                    ("LIQUID", "Liquid"),
                ],
                max_length=20,
                null=True,
                verbose_name="Package Type",
            ),
        ),
        migrations.AlterField(
            model_name="wastebatch",
            name="material",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LIQUID", "Liquid"),
                    (
                        "LIGHTWEIGHT",
                        "Lightweight Materials (Paper, Cloth, Plastic, etc.)",
                    ),
                    ("HEAVY", "Heavy Materials (Metals, Glass, Syringes, etc.)"),
                    ("FILTERS", "Filters"),
                    ("RESINS", "Resins"),
                    ("BIOLOGICAL", "Biological"),
                    ("CHARCOAL", "Charcoal"),
                    ("OTHER", "Other"),
                    ("SPECIAL_OTHER", "Special Other"),
                    ("SOIL_SEDIMENTS_SLUDGE", "Soil, Sediments and Sludge"),
                ],
                max_length=30,
                null=True,
                verbose_name="Material",
            ),
        ),
        migrations.AlterField(
            model_name="wastebatch",
            name="package_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BAG", "Bag"),
                    ("LARGE_BIN", "Large Bin"),
                    ("BOX", "Box"),
                    ("CONTAINER", "Container"),
                    ("DRUM", "Drum"),
                    ("NON_STANDARD", "Non-standard"),
                    ("CAN", "Can"),
                    ("SMALL_BIN", "Small Bin"),
                    ("SMALL_PIPE", "Small Pipe"),
                    ("LIQUID", "Liquid"),
                ],
                max_length=20,
                null=True,
                verbose_name="Package Type",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalWasteReceipt",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "waste_type",
                    models.CharField(
                        choices=[("LIQUID", "Liquid"), ("SOLID", "Solid")],
                        max_length=10,
                        verbose_name="Waste Type",
                    ),
                ),
                (
                    "letter_number",
                    models.CharField(max_length=100, verbose_name="Letter Number"),
                ),
                ("letter_date", models.DateField(verbose_name="Letter Date")),
                (
                    "letter_file",
                    models.TextField(
                        max_length=100,
                        validators=[common.utils.fileValidator.validate_attachment],
                        verbose_name="Letter",
                    ),
                ),
                (
                    "laboratory",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Laboratory / Unit"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Delivery Date"
                    ),
                ),
                (
                    "minutes_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Minutes Number"
                    ),
                ),
                (
                    "minutes_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Minutes Date"
                    ),
                ),
                (
                    "radionuclides",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Radionuclides Present"
                    ),
                ),
                (
                    "waste_origin_place",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Waste Generation Place",
                    ),
                ),
                (
                    "cabin_dose_uSv",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Driver Cabin Dose (µSv/h)",
                    ),
                ),
                (
                    "container_dose_uSv",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Carrier Container Dose (µSv/h)",
                    ),
                ),
                (
                    "deliverer_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Deliverer Representative",
                    ),
                ),
                (
                    "deliverer_position",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Deliverer Position"
                    ),
                ),
                (
                    "receiver_position",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Receiver Position"
                    ),
                ),
                (
                    "signed_minutes_file",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[common.utils.fileValidator.validate_attachment],
                        verbose_name="Signed Minutes",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft (data entry)"),
                            ("MINUTES_READY", "Minutes ready - awaiting signed copy"),
                            ("FINALIZED", "Finalized"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="facilities.facilitymodel",
                        verbose_name="Receiving Facility",
                    ),
                ),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "origin_facility",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="facilities.facilitymodel",
                        verbose_name="Delivering Facility",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Received By (responsible)",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Waste Receipt",
                "verbose_name_plural": "historical Waste Receipts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="WasteReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "waste_type",
                    models.CharField(
                        choices=[("LIQUID", "Liquid"), ("SOLID", "Solid")],
                        max_length=10,
                        verbose_name="Waste Type",
                    ),
                ),
                (
                    "letter_number",
                    models.CharField(max_length=100, verbose_name="Letter Number"),
                ),
                ("letter_date", models.DateField(verbose_name="Letter Date")),
                (
                    "letter_file",
                    models.FileField(
                        upload_to="waste/receipts/letters/",
                        validators=[common.utils.fileValidator.validate_attachment],
                        verbose_name="Letter",
                    ),
                ),
                (
                    "laboratory",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Laboratory / Unit"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Delivery Date"
                    ),
                ),
                (
                    "minutes_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Minutes Number"
                    ),
                ),
                (
                    "minutes_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Minutes Date"
                    ),
                ),
                (
                    "radionuclides",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Radionuclides Present"
                    ),
                ),
                (
                    "waste_origin_place",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Waste Generation Place",
                    ),
                ),
                (
                    "cabin_dose_uSv",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Driver Cabin Dose (µSv/h)",
                    ),
                ),
                (
                    "container_dose_uSv",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Carrier Container Dose (µSv/h)",
                    ),
                ),
                (
                    "deliverer_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Deliverer Representative",
                    ),
                ),
                (
                    "deliverer_position",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Deliverer Position"
                    ),
                ),
                (
                    "receiver_position",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Receiver Position"
                    ),
                ),
                (
                    "signed_minutes_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="waste/receipts/minutes/",
                        validators=[common.utils.fileValidator.validate_attachment],
                        verbose_name="Signed Minutes",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft (data entry)"),
                            ("MINUTES_READY", "Minutes ready - awaiting signed copy"),
                            ("FINALIZED", "Finalized"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waste_receipts",
                        to="facilities.facilitymodel",
                        verbose_name="Receiving Facility",
                    ),
                ),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "origin_facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waste_deliveries",
                        to="facilities.facilitymodel",
                        verbose_name="Delivering Facility",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts_to_complete",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Received By (responsible)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Waste Receipt",
                "verbose_name_plural": "Waste Receipts",
                "ordering": ("-created_at",),
                "permissions": [
                    ("manage_receipts", "Can complete and finalize any waste receipt")
                ],
            },
        ),
        migrations.CreateModel(
            name="WasteReceiptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("LIQUID", "Liquid"),
                            (
                                "LIGHTWEIGHT",
                                "Lightweight Materials (Paper, Cloth, Plastic, etc.)",
                            ),
                            (
                                "HEAVY",
                                "Heavy Materials (Metals, Glass, Syringes, etc.)",
                            ),
                            ("FILTERS", "Filters"),
                            ("RESINS", "Resins"),
                            ("BIOLOGICAL", "Biological"),
                            ("CHARCOAL", "Charcoal"),
                            ("OTHER", "Other"),
                            ("SPECIAL_OTHER", "Special Other"),
                            ("SOIL_SEDIMENTS_SLUDGE", "Soil, Sediments and Sludge"),
                        ],
                        max_length=30,
                        verbose_name="Material",
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("BAG", "Bag"),
                            ("LARGE_BIN", "Large Bin"),
                            ("BOX", "Box"),
                            ("CONTAINER", "Container"),
                            ("DRUM", "Drum"),
                            ("NON_STANDARD", "Non-standard"),
                            ("CAN", "Can"),
                            ("SMALL_BIN", "Small Bin"),
                            ("SMALL_PIPE", "Small Pipe"),
                            ("LIQUID", "Liquid"),
                        ],
                        max_length=20,
                        verbose_name="Package Type",
                    ),
                ),
                (
                    "package_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Number of Packages"
                    ),
                ),
                (
                    "mass_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Mass (kg)",
                    ),
                ),
                (
                    "volume_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Volume (m³)",
                    ),
                ),
                (
                    "surface_dose_uSv",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Surface Dose (µSv/h)",
                    ),
                ),
                (
                    "half_life",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Half-life"
                    ),
                ),
                (
                    "half_life_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LT100", "Half-life < 100 days"),
                            ("GT100", "Half-life > 100 days"),
                        ],
                        max_length=5,
                        verbose_name="Half-life Class",
                    ),
                ),
                (
                    "alpha_bq_l",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Alpha (Bq/L)",
                    ),
                ),
                (
                    "beta_bq_l",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Beta (Bq/L)",
                    ),
                ),
                (
                    "gamma_bq_l",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Gamma (Bq/L)",
                    ),
                ),
                (
                    "ph",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="pH",
                    ),
                ),
                (
                    "density",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Density",
                    ),
                ),
                (
                    "hardness",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Hardness",
                    ),
                ),
                (
                    "batch",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_line",
                        to="waste.wastebatch",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="waste.wastereceipt",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="wastereceipt",
            constraint=models.UniqueConstraint(
                fields=("origin_facility", "letter_number"),
                name="uniq_receipt_letter_per_origin",
            ),
        ),
        migrations.AddConstraint(
            model_name="wastereceiptline",
            constraint=models.UniqueConstraint(
                fields=("receipt", "material", "package_type"),
                name="uniq_line_material_package",
            ),
        ),
    ]
