# Generated by Django 6.0.6 on 2026-10-07 05:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste", "0005_wasteidcounter_historicalwastebatch_hardness_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wastereceiptline",
            name="package_count",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Solid waste: one waste record is created per package.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Number of Packages",
            ),
        ),
        migrations.CreateModel(
            name="WasteReceiptPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(verbose_name="Package No.")),
                (
                    "batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_package",
                        to="waste.wastebatch",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="waste.wastereceiptline",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("line", "sequence"),
                        name="uniq_package_sequence_per_line",
                    )
                ],
            },
        ),
    ]
