# Generated by Django 6.0.6 on 2026-10-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0005_alter_nuclides_d_value_bq_alter_nuclides_half_life"),
        ("waste", "0006_alter_wastereceiptline_package_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalwastereceipt",
            name="radionuclides",
        ),
        migrations.RemoveField(
            model_name="historicalwastereceipt",
            name="receiver_position",
        ),
        migrations.RemoveField(
            model_name="wastereceipt",
            name="radionuclides",
        ),
        migrations.RemoveField(
            model_name="wastereceipt",
            name="receiver_position",
        ),
        migrations.AddField(
            model_name="wastereceipt",
            name="nuclides",
            field=models.ManyToManyField(
                blank=True,
                related_name="waste_receipts",
                to="reference.nuclides",
                verbose_name="Radionuclides Present",
            ),
        ),
    ]
