# Generated by Django 6.0.6 on 2026-09-02 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facilities", "0003_remove_facilitymodel_unique_facility_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiveSourceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letter_number", models.CharField(max_length=100)),
                ("letter_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SPECIFICATION", "Specification"),
                            ("WAITING_OPERATION_MANAGER", "Waiting Operation Manager"),
                            (
                                "WAITING_OPERATION_CONTROL_MANAGER",
                                "Waiting Operation Control Manager",
                            ),
                            ("WAITING_DEPUTY_MANAGER", "Waiting Deputy Manager"),
                            ("WAITING_CONTRACT", "Waiting Contract"),
                            ("WAITING_PAYMENT", "Waiting Payment"),
                            (
                                "WAITING_FINANCIAL_APPROVAL",
                                "Waiting Financial Approval",
                            ),
                            ("WAITING_CEO_APPROVAL", "Waiting CEO Approval"),
                            ("RECEIVING", "Receiving Source"),
                            ("CHARACTERIZATION", "Characterization"),
                            ("STORED", "Stored"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                ("discount_requested", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_receive_source_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receive_source_requests",
                        to="facilities.facilitymodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceiveSourceAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("LETTER", "Request Letter"),
                            ("INQUIRY_FORM", "DSRS Inquiry Form"),
                            ("LICENSE", "License"),
                            ("CONTRACT", "Contract"),
                            ("RECEIVING_DOCUMENT", "Receiving Document"),
                            ("CERTIFICATE", "Certificate"),
                            ("PHOTO", "Photo"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="receive_source/attachments/")),
                ("description", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="receive_source.receivesourcerequest",
                    ),
                ),
            ],
        ),
    ]
