# Generated by Django 6.0.6 on 2026-09-05 05:15

import django.db.models.deletion
import receive_source.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_alter_dsrs_options_alter_hideshowfiltert_options_and_more"),
        ("facilities", "0003_remove_facilitymodel_unique_facility_name_and_more"),
        ("receive_source", "0001_initial"),
        ("reference", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receivesourcerequest",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="receivesourcerequest",
            name="facility",
        ),
        migrations.CreateModel(
            name="HistoricalReceiveRequest",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "inquiry_letter_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Inquiry Letter Number",
                    ),
                ),
                (
                    "inquiry_letter_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Inquiry Letter Date"
                    ),
                ),
                (
                    "distance_to_tehran_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Estimated Distance to Tehran Office (km)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SPECIFICATION", "Preparing Specification"),
                            (
                                "WAITING_CREATOR",
                                "Waiting Creator/Coordinator Signature",
                            ),
                            ("WAITING_MANAGER_INPUT", "Waiting Manager Data Entry"),
                            ("WAITING_MANAGER", "Waiting Operation Manager Signature"),
                            (
                                "WAITING_CONTROL",
                                "Waiting Operation Control Manager Signature",
                            ),
                            ("WAITING_DEPUTY", "Waiting Deputy Manager Signature"),
                            ("CONTRACTS", "Contracts"),
                            (
                                "WAITING_CEO",
                                "Waiting CEO Signature (Discount Requested)",
                            ),
                            ("FINANCE", "Finance"),
                            ("READY_TO_RECEIVE", "Ready To Receive"),
                            ("RECEIVING", "Receiving / Characterization"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=25,
                        verbose_name="Status",
                    ),
                ),
                (
                    "status_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Status Date"
                    ),
                ),
                (
                    "specification_completed",
                    models.BooleanField(
                        default=False, verbose_name="Specification Completed"
                    ),
                ),
                (
                    "pre_operation_visit_needed",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Pre-Operation Visit Needed"
                    ),
                ),
                (
                    "dispatched_expert_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Dispatched Experts"
                    ),
                ),
                (
                    "dispatched_technician_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Dispatched Technicians"
                    ),
                ),
                (
                    "dispatched_driver_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Dispatched Drivers"
                    ),
                ),
                (
                    "mission_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Mission Days"
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GASOLINE", "Gasoline"),
                            ("DIESEL", "Diesel"),
                            ("AIRPLANE", "Airplane"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Vehicle Type",
                    ),
                ),
                (
                    "route_difficulty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NORMAL", "Normal"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Route Difficulty",
                    ),
                ),
                (
                    "accommodation_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Accommodation Days"
                    ),
                ),
                (
                    "food_cost_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Food Cost Days"
                    ),
                ),
                (
                    "peripheral_equipment",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Peripheral Equipment Used",
                    ),
                ),
                (
                    "other_costs",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Other Costs",
                    ),
                ),
                (
                    "logistics_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Logistics Notes"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Updated At"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="facilities.facilitymodel",
                        verbose_name="Delivering Facility",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Receive Request",
                "verbose_name_plural": "historical Receive Requests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ReceiveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inquiry_letter_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Inquiry Letter Number",
                    ),
                ),
                (
                    "inquiry_letter_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Inquiry Letter Date"
                    ),
                ),
                (
                    "distance_to_tehran_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Estimated Distance to Tehran Office (km)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SPECIFICATION", "Preparing Specification"),
                            (
                                "WAITING_CREATOR",
                                "Waiting Creator/Coordinator Signature",
                            ),
                            ("WAITING_MANAGER_INPUT", "Waiting Manager Data Entry"),
                            ("WAITING_MANAGER", "Waiting Operation Manager Signature"),
                            (
                                "WAITING_CONTROL",
                                "Waiting Operation Control Manager Signature",
                            ),
                            ("WAITING_DEPUTY", "Waiting Deputy Manager Signature"),
                            ("CONTRACTS", "Contracts"),
                            (
                                "WAITING_CEO",
                                "Waiting CEO Signature (Discount Requested)",
                            ),
                            ("FINANCE", "Finance"),
                            ("READY_TO_RECEIVE", "Ready To Receive"),
                            ("RECEIVING", "Receiving / Characterization"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=25,
                        verbose_name="Status",
                    ),
                ),
                (
                    "status_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Status Date"
                    ),
                ),
                (
                    "specification_completed",
                    models.BooleanField(
                        default=False, verbose_name="Specification Completed"
                    ),
                ),
                (
                    "pre_operation_visit_needed",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Pre-Operation Visit Needed"
                    ),
                ),
                (
                    "dispatched_expert_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Dispatched Experts"
                    ),
                ),
                (
                    "dispatched_technician_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Dispatched Technicians"
                    ),
                ),
                (
                    "dispatched_driver_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Dispatched Drivers"
                    ),
                ),
                (
                    "mission_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Mission Days"
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GASOLINE", "Gasoline"),
                            ("DIESEL", "Diesel"),
                            ("AIRPLANE", "Airplane"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Vehicle Type",
                    ),
                ),
                (
                    "route_difficulty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NORMAL", "Normal"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Route Difficulty",
                    ),
                ),
                (
                    "accommodation_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Accommodation Days"
                    ),
                ),
                (
                    "food_cost_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Food Cost Days"
                    ),
                ),
                (
                    "peripheral_equipment",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Peripheral Equipment Used",
                    ),
                ),
                (
                    "other_costs",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Other Costs",
                    ),
                ),
                (
                    "logistics_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Logistics Notes"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receive_requests_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receive_requests",
                        to="facilities.facilitymodel",
                        verbose_name="Delivering Facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receive Request",
                "verbose_name_plural": "Receive Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceivePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_done",
                    models.BooleanField(
                        default=False, verbose_name="Payment Completed"
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Payment Date"
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Amount Paid",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "receive_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="receive_source.receiverequest",
                        verbose_name="Receive Request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receive Payment",
                "verbose_name_plural": "Receive Payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceiveContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Contract Number",
                    ),
                ),
                (
                    "contract_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Contract Date"
                    ),
                ),
                (
                    "contract_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Contract Cost",
                    ),
                ),
                (
                    "discount_requested",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, the request routes to the CEO for signature before Finance.",
                        verbose_name="Discount Requested",
                    ),
                ),
                (
                    "discount_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Discount Notes"
                    ),
                ),
                (
                    "send_to_financial",
                    models.BooleanField(
                        default=False, verbose_name="Send to Financial"
                    ),
                ),
                (
                    "contract_accountable",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Contract Accountable",
                    ),
                ),
                (
                    "amendment_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Amendment Notes"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "receive_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract",
                        to="receive_source.receiverequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receive Contract",
                "verbose_name_plural": "Receive Contracts",
            },
        ),
        migrations.CreateModel(
            name="ReceiveAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("INQUIRY", "DSRS Inquiry Letter"),
                            ("LETTER", "Letter"),
                            ("SPECIFICATION", "Generated Specification"),
                            ("SPECIFICATION_APPENDIX", "Specification Appendix"),
                            ("CONTRACT", "Contract"),
                            ("PAYMENT", "Payment Receipt"),
                            ("CHARACTERIZATION", "Characterization Document"),
                            ("OTHER", "Other"),
                        ],
                        max_length=25,
                        verbose_name="Attachment Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=receive_source.models.receive_attachment_path,
                        verbose_name="File",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receive_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="receive_source.receiverequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receive Attachment",
                "verbose_name_plural": "Receive Attachments",
                "ordering": ["attachment_type"],
            },
        ),
        migrations.CreateModel(
            name="ReceiveApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("CREATOR", "Creator / Coordinator"),
                            ("MANAGER", "Operation Manager"),
                            ("CONTROL", "Operation Control Manager"),
                            ("DEPUTY", "Deputy Manager"),
                            ("CEO", "CEO"),
                        ],
                        max_length=15,
                        verbose_name="Approval Step",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("NOT_REQUIRED", "Not Required"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Comments")),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approver",
                    ),
                ),
                (
                    "receive_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="receive_source.receiverequest",
                        verbose_name="Receive Request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receive Approval",
                "verbose_name_plural": "Receive Approvals",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalReceivePayment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "payment_done",
                    models.BooleanField(
                        default=False, verbose_name="Payment Completed"
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Payment Date"
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Amount Paid",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Updated At"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receive_request",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="receive_source.receiverequest",
                        verbose_name="Receive Request",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Receive Payment",
                "verbose_name_plural": "historical Receive Payments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalReceiveContract",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Contract Number",
                    ),
                ),
                (
                    "contract_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Contract Date"
                    ),
                ),
                (
                    "contract_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Contract Cost",
                    ),
                ),
                (
                    "discount_requested",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, the request routes to the CEO for signature before Finance.",
                        verbose_name="Discount Requested",
                    ),
                ),
                (
                    "discount_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Discount Notes"
                    ),
                ),
                (
                    "send_to_financial",
                    models.BooleanField(
                        default=False, verbose_name="Send to Financial"
                    ),
                ),
                (
                    "contract_accountable",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Contract Accountable",
                    ),
                ),
                (
                    "amendment_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Amendment Notes"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Updated At"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receive_request",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="receive_source.receiverequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Receive Contract",
                "verbose_name_plural": "historical Receive Contracts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalReceiveApproval",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("CREATOR", "Creator / Coordinator"),
                            ("MANAGER", "Operation Manager"),
                            ("CONTROL", "Operation Control Manager"),
                            ("DEPUTY", "Deputy Manager"),
                            ("CEO", "CEO"),
                        ],
                        max_length=15,
                        verbose_name="Approval Step",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("NOT_REQUIRED", "Not Required"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Comments")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approver",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receive_request",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="receive_source.receiverequest",
                        verbose_name="Receive Request",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Receive Approval",
                "verbose_name_plural": "historical Receive Approvals",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ReceiveSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("SOURCE", "Radioactive Source"),
                            ("WASTE", "Radioactive Waste"),
                        ],
                        default="SOURCE",
                        max_length=10,
                        verbose_name="Item Type",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Not printed on the form — used only to check for an existing license contract.",
                        max_length=150,
                        null=True,
                        verbose_name="Serial Number",
                    ),
                ),
                (
                    "average_activity_mci",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=15,
                        null=True,
                        verbose_name="Average Activity (mCi)",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantity"),
                ),
                (
                    "half_life_display",
                    models.CharField(
                        blank=True,
                        help_text="Prefilled from the nuclide record; editable if needed.",
                        max_length=50,
                        null=True,
                        verbose_name="Half-Life",
                    ),
                ),
                (
                    "needs_shield",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Needs Shield"
                    ),
                ),
                (
                    "needs_burial",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Needs Burial"
                    ),
                ),
                (
                    "storage_duration",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Storage Duration",
                    ),
                ),
                (
                    "sale_probability",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Sale Probability",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Auto-annotated with license-contract match, if any.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "specification_order",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Specification Order"
                    ),
                ),
                (
                    "nuclide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reference.nuclides",
                        verbose_name="Nuclide",
                    ),
                ),
                (
                    "receive_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="receive_source.receiverequest",
                        verbose_name="Receive Request",
                    ),
                ),
                (
                    "result_dsrs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_by_receive_sources",
                        to="dashboard.dsrs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receive Source",
                "verbose_name_plural": "Receive Sources",
                "ordering": ["specification_order", "id"],
            },
        ),
        migrations.DeleteModel(
            name="ReceiveSourceAttachment",
        ),
        migrations.DeleteModel(
            name="ReceiveSourceRequest",
        ),
    ]
