# Generated by Django 6.0.6 on 2026-09-05 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_alter_dsrs_options_alter_hideshowfiltert_options_and_more"),
        ("receive_source", "0002_remove_receivesourcerequest_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalreceiverequest",
            name="dispatched_driver_count",
        ),
        migrations.RemoveField(
            model_name="historicalreceiverequest",
            name="dispatched_expert_count",
        ),
        migrations.RemoveField(
            model_name="historicalreceiverequest",
            name="dispatched_technician_count",
        ),
        migrations.RemoveField(
            model_name="historicalreceiverequest",
            name="mission_days",
        ),
        migrations.RemoveField(
            model_name="historicalreceiverequest",
            name="vehicle_type",
        ),
        migrations.RemoveField(
            model_name="receiverequest",
            name="dispatched_driver_count",
        ),
        migrations.RemoveField(
            model_name="receiverequest",
            name="dispatched_expert_count",
        ),
        migrations.RemoveField(
            model_name="receiverequest",
            name="dispatched_technician_count",
        ),
        migrations.RemoveField(
            model_name="receiverequest",
            name="mission_days",
        ),
        migrations.RemoveField(
            model_name="receiverequest",
            name="vehicle_type",
        ),
        migrations.AddField(
            model_name="historicalreceiverequest",
            name="operation_driver_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Operation: Drivers"
            ),
        ),
        migrations.AddField(
            model_name="historicalreceiverequest",
            name="operation_expert_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Operation: Experts"
            ),
        ),
        migrations.AddField(
            model_name="historicalreceiverequest",
            name="operation_mission_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Operation: Mission Days"
            ),
        ),
        migrations.AddField(
            model_name="historicalreceiverequest",
            name="operation_technician_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Operation: Technicians"
            ),
        ),
        migrations.AddField(
            model_name="historicalreceiverequest",
            name="operation_vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GASOLINE", "Gasoline"),
                    ("DIESEL", "Diesel"),
                    ("AIRPLANE", "Airplane"),
                ],
                max_length=10,
                null=True,
                verbose_name="Operation: Vehicle Type",
            ),
        ),
        migrations.AddField(
            model_name="historicalreceiverequest",
            name="visit_driver_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Visit: Drivers"
            ),
        ),
        migrations.AddField(
            model_name="historicalreceiverequest",
            name="visit_expert_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Visit: Experts"
            ),
        ),
        migrations.AddField(
            model_name="historicalreceiverequest",
            name="visit_mission_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Visit: Mission Days"
            ),
        ),
        migrations.AddField(
            model_name="historicalreceiverequest",
            name="visit_technician_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Visit: Technicians"
            ),
        ),
        migrations.AddField(
            model_name="historicalreceiverequest",
            name="visit_vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GASOLINE", "Gasoline"),
                    ("DIESEL", "Diesel"),
                    ("AIRPLANE", "Airplane"),
                ],
                max_length=10,
                null=True,
                verbose_name="Visit: Vehicle Type",
            ),
        ),
        migrations.AddField(
            model_name="receiverequest",
            name="operation_driver_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Operation: Drivers"
            ),
        ),
        migrations.AddField(
            model_name="receiverequest",
            name="operation_expert_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Operation: Experts"
            ),
        ),
        migrations.AddField(
            model_name="receiverequest",
            name="operation_mission_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Operation: Mission Days"
            ),
        ),
        migrations.AddField(
            model_name="receiverequest",
            name="operation_technician_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Operation: Technicians"
            ),
        ),
        migrations.AddField(
            model_name="receiverequest",
            name="operation_vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GASOLINE", "Gasoline"),
                    ("DIESEL", "Diesel"),
                    ("AIRPLANE", "Airplane"),
                ],
                max_length=10,
                null=True,
                verbose_name="Operation: Vehicle Type",
            ),
        ),
        migrations.AddField(
            model_name="receiverequest",
            name="visit_driver_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Visit: Drivers"
            ),
        ),
        migrations.AddField(
            model_name="receiverequest",
            name="visit_expert_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Visit: Experts"
            ),
        ),
        migrations.AddField(
            model_name="receiverequest",
            name="visit_mission_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Visit: Mission Days"
            ),
        ),
        migrations.AddField(
            model_name="receiverequest",
            name="visit_technician_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Visit: Technicians"
            ),
        ),
        migrations.AddField(
            model_name="receiverequest",
            name="visit_vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GASOLINE", "Gasoline"),
                    ("DIESEL", "Diesel"),
                    ("AIRPLANE", "Airplane"),
                ],
                max_length=10,
                null=True,
                verbose_name="Visit: Vehicle Type",
            ),
        ),
        migrations.AddField(
            model_name="receivesource",
            name="matched_license_dsrs",
            field=models.ForeignKey(
                blank=True,
                help_text="Set automatically on an exact serial match, or manually confirmed by the creator on a fuzzy match.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="dashboard.dsrs",
                verbose_name="Matched Existing Licensed Source",
            ),
        ),
        migrations.AddField(
            model_name="receivesource",
            name="serial_matched_exactly",
            field=models.BooleanField(
                default=False, verbose_name="Serial Matched Exactly"
            ),
        ),
        migrations.AlterField(
            model_name="historicalreceiverequest",
            name="other_costs",
            field=models.CharField(
                blank=True,
                help_text="Also where the cost of an unmatched/no-license item gets folded in, per current policy.",
                max_length=255,
                null=True,
                verbose_name="Other Costs",
            ),
        ),
        migrations.AlterField(
            model_name="receiverequest",
            name="other_costs",
            field=models.CharField(
                blank=True,
                help_text="Also where the cost of an unmatched/no-license item gets folded in, per current policy.",
                max_length=255,
                null=True,
                verbose_name="Other Costs",
            ),
        ),
        migrations.AlterField(
            model_name="receivesource",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Auto-annotated with a license-contract match, if any (see below).",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="receivesource",
            name="half_life_display",
            field=models.CharField(
                blank=True,
                help_text="Auto-formatted from nuclide.half_life (stored in seconds) at save time — not user-entered. Kept as a display snapshot since the printed form shows it as static text.",
                max_length=50,
                null=True,
                verbose_name="Half-Life",
            ),
        ),
    ]
