# Generated by Django 6.0.6 on 2026-09-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_dsrs_options_alter_hideshowfiltert_options_and_more'),
        ('receive_source', '0004_remove_historicalreceiverequest_accommodation_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreceivecontract',
            name='invoice',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='historicalreceivepayment',
            name='receipt',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Payment Receipt'),
        ),
        migrations.AddField(
            model_name='receivecontract',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='receiving/invoices/', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='receivepayment',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receiving/payment_receipts/', verbose_name='Payment Receipt'),
        ),
        migrations.RemoveField(
            model_name='receivesource',
            name='result_dsrs',
        ),
        migrations.AddField(
            model_name='receivesource',
            name='result_dsrs',
            field=models.ManyToManyField(blank=True, related_name='created_by_receive_sources', to='dashboard.dsrs'),
        ),
    ]
