# Generated by Django 6.0.6 on 2026-09-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_dsrs_options_alter_hideshowfiltert_options_and_more'),
        ('receive_source', '0005_historicalreceivecontract_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivesource',
            name='initial_movements',
            field=models.ManyToManyField(blank=True, related_name='+', to='dashboard.sourcemovement'),
        ),
    ]
