# Generated by Django 6.0.6 on 2026-09-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receive_source', '0006_receivesource_initial_movements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivesource',
            name='initial_movements',
        ),
        migrations.AddField(
            model_name='historicalreceiverequest',
            name='discount_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Discount Notes'),
        ),
        migrations.AddField(
            model_name='historicalreceiverequest',
            name='discount_requested',
            field=models.BooleanField(default=False, verbose_name='Discount Requested'),
        ),
        migrations.AddField(
            model_name='receiverequest',
            name='discount_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Discount Notes'),
        ),
        migrations.AddField(
            model_name='receiverequest',
            name='discount_requested',
            field=models.BooleanField(default=False, verbose_name='Discount Requested'),
        ),
        migrations.AlterField(
            model_name='receiveattachment',
            name='attachment_type',
            field=models.CharField(choices=[('INQUIRY', 'DSRS Inquiry Letter'), ('LETTER', 'Letter'), ('SPECIFICATION', 'Generated Specification'), ('SPECIFICATION_APPENDIX', 'Specification Appendix'), ('CONTRACT', 'Contract'), ('PAYMENT', 'Payment Receipt'), ('CHARACTERIZATION', 'Characterization Document (صورتجلسه staging)'), ('OTHER', 'Other')], max_length=25, verbose_name='Attachment Type'),
        ),
    ]
