# Generated by Django 6.0.6 on 2026-09-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receive_source', '0007_remove_receivesource_initial_movements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreceiverequest',
            name='inquiry_letter_date',
        ),
        migrations.RemoveField(
            model_name='historicalreceiverequest',
            name='inquiry_letter_number',
        ),
        migrations.RemoveField(
            model_name='receiverequest',
            name='inquiry_letter_date',
        ),
        migrations.RemoveField(
            model_name='receiverequest',
            name='inquiry_letter_number',
        ),
        migrations.AddField(
            model_name='historicalreceiverequest',
            name='delivery_letter_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery Letter Date'),
        ),
        migrations.AddField(
            model_name='historicalreceiverequest',
            name='derivery_letter_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Delivery Letter Number'),
        ),
        migrations.AddField(
            model_name='receiverequest',
            name='delivery_letter_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery Letter Date'),
        ),
        migrations.AddField(
            model_name='receiverequest',
            name='derivery_letter_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Delivery Letter Number'),
        ),
        migrations.AlterField(
            model_name='receiveattachment',
            name='attachment_type',
            field=models.CharField(choices=[('INQUIRY', 'DSRS Inquiry Form'), ('LETTER', 'Letter'), ('SPECIFICATION', 'Generated Specification'), ('SPECIFICATION_APPENDIX', 'Specification Appendix'), ('CONTRACT', 'Contract'), ('PAYMENT', 'Payment Receipt'), ('CHARACTERIZATION', 'Characterization Document (صورتجلسه staging)'), ('OTHER', 'Other')], max_length=25, verbose_name='Attachment Type'),
        ),
    ]
