# Generated by Django 6.0.6 on 2026-09-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receive_source', '0008_remove_historicalreceiverequest_inquiry_letter_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalreceiverequest',
            old_name='derivery_letter_number',
            new_name='delivery_letter_number',
        ),
        migrations.RenameField(
            model_name='receiverequest',
            old_name='derivery_letter_number',
            new_name='delivery_letter_number',
        ),
    ]
