# Generated by Django 6.0.6 on 2026-07-19 08:27

import django.db.models.deletion
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0017_alter_dsrs_nuclide_alter_historicaldsrs_nuclide_and_more"),
        ("facilities", "0003_remove_facility_is_active"),
        ("reference", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "letter_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("letter_date", models.DateField(blank=True, null=True)),
                (
                    "contract_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("contract_date", models.DateField(blank=True, null=True)),
                (
                    "contract_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OCR", "OCR"),
                            ("SIGNATURE", "Waiting Signature"),
                            ("CONTRACT", "Contract"),
                            ("FINANCE", "Finance"),
                            ("ISSUED", "Issued"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="license_requests",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LicenseDSRS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "activity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("activity_date", models.DateField(blank=True, null=True)),
                (
                    "dsrs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.dsrs",
                    ),
                ),
                (
                    "nuclide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reference.nuclides",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license_dsrss",
                        to="operations.licenserequest",
                    ),
                ),
            ],
            options={
                "ordering": ["serial_number"],
            },
        ),
        migrations.CreateModel(
            name="LicenseAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("LETTER", "Letter"),
                            ("COMMITMENT", "Commitment"),
                            ("PERMIT", "Permit"),
                            ("INQUIRY", "DSRS Inquiry"),
                            ("CONTRACT", "Contract"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Attachment Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=operations.models.license_attachment_path,
                        verbose_name="File",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="operations.licenserequest",
                    ),
                ),
            ],
            options={
                "ordering": ["attachment_type"],
            },
        ),
    ]
