# Generated by Django 6.0.6 on 2026-07-26 08:10

import django.db.models.deletion
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0001_initial"),
        ("facilities", "0001_initial"),
        ("reference", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "letter_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("letter_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SPECIFICATION", "Preparing Specification"),
                            ("WAITING_CREATOR", "Waiting Creator Signature"),
                            ("WAITING_MANAGER", "Waiting Manager Signature"),
                            ("WAITING_DEPUTY", "Waiting Deputy Signature"),
                            ("CONTRACTS", "Contracts"),
                            ("FINANCE", "Finance"),
                            ("READY_TO_ISSUE", "Ready To Issue"),
                            ("ISSUED", "Issued"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("status_date", models.DateTimeField(blank=True, null=True)),
                ("specification_completed", models.BooleanField(default=False)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="license_requests",
                        to="facilities.facilitymodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LicenseAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("LETTER", "Letter"),
                            ("COMMITMENT", "Commitment"),
                            ("PERMIT", "Permit"),
                            ("INQUIRY", "DSRS Inquiry"),
                            ("CONTRACT", "Contract"),
                            ("SPECIFICATION", "Generated Specification"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Attachment Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=operations.models.license_attachment_path,
                        verbose_name="File",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="operations.licenserequest",
                    ),
                ),
            ],
            options={
                "ordering": ["attachment_type"],
            },
        ),
        migrations.CreateModel(
            name="LicenseApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("CREATOR", "Creator"),
                            ("MANAGER", "Manager"),
                            ("DEPUTY", "Deputy Manager"),
                            ("CONTRACTS", "Contracts"),
                        ],
                        max_length=30,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("comments", models.TextField(blank=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="operations.licenserequest",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LicenseSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("NEW", "New Source"),
                            ("REUSED", "Reused Source"),
                            ("RECYCLED", "Recycled Source"),
                        ],
                        default="NEW",
                        max_length=15,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Serial Number"
                    ),
                ),
                (
                    "activity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=15,
                        null=True,
                        verbose_name="Activity",
                    ),
                ),
                (
                    "activity_unit",
                    models.CharField(
                        choices=[
                            ("Bq", "Bq"),
                            ("KBq", "KBq"),
                            ("MBq", "MBq"),
                            ("GBq", "GBq"),
                            ("Ci", "Ci"),
                            ("mCi", "mCi"),
                            ("uCi", "uCi"),
                            ("nCi", "nCi"),
                        ],
                        default="mCi",
                        max_length=20,
                        verbose_name="Activity Unit",
                    ),
                ),
                (
                    "activity_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Activity Date"
                    ),
                ),
                ("specification_order", models.PositiveIntegerField(default=1)),
                ("description", models.TextField(blank=True, max_length=50, null=True)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="operations.licenserequest",
                        verbose_name="License",
                    ),
                ),
                (
                    "nuclide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reference.nuclides",
                        verbose_name="Nuclide",
                    ),
                ),
                (
                    "result_dsrs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_by_licenses",
                        to="dashboard.dsrs",
                    ),
                ),
                (
                    "source_dsrs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_in_licenses",
                        to="dashboard.dsrs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requested Source",
                "verbose_name_plural": "Requested Sources",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="UserSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signature", models.ImageField(upload_to="signatures/")),
                ("title", models.CharField(blank=True, max_length=150)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
