# Generated by Django 6.0.6 on 2026-07-18 07:50

import django.db.models.deletion
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facilities", "0003_remove_facility_is_active"),
        ("reference", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_number",
                    models.CharField(
                        blank=True,
                        help_text="Unique operation number.",
                        max_length=30,
                        unique=True,
                        verbose_name="Operation Number",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("ISSUE_LICENCE", "Issue Licence"),
                            ("RECEIVE_SOURCE", "Receive Source"),
                            ("RECEIVE_WASTE", "Receive Waste"),
                            ("SELL_SOURCE", "Sell Source"),
                        ],
                        max_length=30,
                        verbose_name="Operation Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OCR_RUNNING", "OCR Running"),
                            ("WAITING_REVIEW", "Waiting Review"),
                            ("WAITING_SIGNATURE", "Waiting Signature"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="DRAFT",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_operations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="facilities.facility",
                        verbose_name="Facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation",
                "verbose_name_plural": "Operations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OperationAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("LETTER", "Letter"),
                            (
                                "SOURCE_INQUIRY",
                                "Radioactive Source Specification Inquiry",
                            ),
                            ("REGULATORY_PERMIT", "Regulatory Permit"),
                            ("COMMITMENT", "Commitment Letter"),
                            ("OTHER", "Other"),
                        ],
                        max_length=40,
                        verbose_name="Attachment Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="A descriptive title for this document (for example: Licence Letter, Purchase Contract).",
                        max_length=200,
                        verbose_name="Attachment Title",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload document file.",
                        upload_to=operations.models.operation_attachment_path,
                        verbose_name="File",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Original Filename"
                    ),
                ),
                (
                    "ocr_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="OCR Status",
                    ),
                ),
                (
                    "ocr_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="OCR confidence percentage if available.",
                        max_digits=5,
                        null=True,
                        verbose_name="OCR Confidence",
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(blank=True, verbose_name="Extracted Text"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        help_text="Operation associated with this attachment.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="operations.operation",
                        verbose_name="Operation",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_operation_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation Attachment",
                "verbose_name_plural": "Operation Attachments",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="OperationSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("COORDINATOR", "Coordinator"),
                            ("OPERATION_MANAGER", "Operation Manager"),
                            ("TECHNICAL_MANAGER", "Technical Manager"),
                            ("DEPUTY_MANAGER", "Deputy Manager"),
                            ("DIRECTOR", "Director"),
                        ],
                        help_text="Required approval role for this operation.",
                        max_length=30,
                        verbose_name="Signature Role",
                    ),
                ),
                ("signed", models.BooleanField(default=False, verbose_name="Signed")),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Signed At"
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="Remarks")),
                (
                    "operation",
                    models.ForeignKey(
                        help_text="Operation requiring this signature.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="operations.operation",
                        verbose_name="Operation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User responsible for signing this operation.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operation_signatures",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Signer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation Signature",
                "verbose_name_plural": "Operation Signatures",
                "ordering": ["role"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("operation", "role"),
                        name="unique_operation_signature_role",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OperationSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_model",
                    models.CharField(
                        blank=True,
                        help_text="Manufacturer or source model.",
                        max_length=200,
                        verbose_name="Source Model",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Manufacturer serial number.",
                        max_length=100,
                        verbose_name="Serial Number",
                    ),
                ),
                (
                    "activity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Source activity.",
                        max_digits=18,
                        null=True,
                        verbose_name="Activity",
                    ),
                ),
                (
                    "activity_unit",
                    models.CharField(
                        blank=True,
                        help_text="For example: Bq, kBq, MBq, GBq, Ci, mCi.",
                        max_length=20,
                        null=True,
                        verbose_name="Activity Unit",
                    ),
                ),
                (
                    "half_life",
                    models.CharField(
                        blank=True,
                        help_text="Optional half-life information.",
                        max_length=100,
                        verbose_name="Half-life",
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="Remarks")),
                (
                    "nuclides",
                    models.ManyToManyField(
                        blank=True,
                        help_text="One or more radionuclides contained in this source.",
                        related_name="operation_sources",
                        to="reference.nuclides",
                        verbose_name="Nuclides",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        help_text="Operation associated with this radioactive source.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="operations.operation",
                        verbose_name="Operation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation Source",
                "verbose_name_plural": "Operation Sources",
                "ordering": ["serial_number"],
                "indexes": [
                    models.Index(
                        fields=["serial_number"], name="operations__serial__441573_idx"
                    )
                ],
            },
        ),
    ]
