# Generated by Django 6.0.5 on 2026-06-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatmentoperation",
            name="treatment_type",
            field=models.CharField(
                choices=[
                    ("CHEMICAL", "Chemical Treatment"),
                    ("SEDIMENTATION", "Sedimentation"),
                    ("FILTRATION", "Filtration"),
                    ("INCINERATION", "Incineration"),
                    ("RETREATMENT", "Retreatment"),
                ],
                max_length=30,
            ),
        ),
    ]
