# Generated by Django 6.0.6 on 2026-07-26 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
        ("reference", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licensesource",
            name="nuclide",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="reference.nuclides",
                verbose_name="Nuclide",
            ),
        ),
    ]
