# Generated by Django 6.0.6 on 2026-07-19 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_alter_dsrs_source_type_alter_dsrs_activity_unit_and_more"),
        ("operations", "0001_initial"),
        ("reference", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Serial Number"
                    ),
                ),
                (
                    "activity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=15,
                        null=True,
                        verbose_name="Activity",
                    ),
                ),
                (
                    "activity_unit",
                    models.CharField(
                        choices=[
                            ("Bq", "Bq"),
                            ("kBq", "kBq"),
                            ("MBq", "MBq"),
                            ("GBq", "GBq"),
                            ("Ci", "Ci"),
                            ("mCi", "mCi"),
                            ("µCi", "µCi"),
                        ],
                        default="mCi",
                        max_length=20,
                        verbose_name="Activity Unit",
                    ),
                ),
                (
                    "activity_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Activity Date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_dsrs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="license_sources",
                        to="dashboard.dsrs",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="operations.licenserequest",
                        verbose_name="License",
                    ),
                ),
                (
                    "nuclide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reference.nuclides",
                        verbose_name="Nuclide",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requested Source",
                "verbose_name_plural": "Requested Sources",
                "ordering": ["id"],
            },
        ),
        migrations.DeleteModel(
            name="LicenseDSRS",
        ),
    ]
