# Generated by Django 6.0.6 on 2026-07-18 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationOCR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_text", models.TextField(blank=True)),
                ("extracted_data", models.JSONField(blank=True, default=dict)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("reviewed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr",
                        to="operations.operation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation OCR",
                "verbose_name_plural": "Operation OCR",
            },
        ),
    ]
