# Generated by Django 6.0.6 on 2026-07-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_licensesource_delete_licensedsrs"),
    ]

    operations = [
        migrations.AddField(
            model_name="licensesource",
            name="specification_order",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
