# Generated by Django 6.0.6 on 2026-07-27 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_remove_sourcemovement_attachment_movementattachment"),
        ("operations", "0002_alter_licensesource_nuclide"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseSourceComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_used", models.PositiveIntegerField(default=1)),
                (
                    "dsrs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="used_in_license_components",
                        to="dashboard.dsrs",
                    ),
                ),
                (
                    "license_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="operations.licensesource",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
