# Generated by Django 6.0.6 on 2026-07-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0003_licensesource_specification_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenserequest",
            name="specification_completed",
            field=models.BooleanField(default=False),
        ),
    ]
