# Generated by Django 6.0.6 on 2026-07-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0004_licenserequest_specification_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="licensesource",
            name="notes",
        ),
        migrations.AddField(
            model_name="licensesource",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Additional Description",
                null=True,
                verbose_name="Description",
            ),
        ),
    ]
