# Generated by Django 6.0.6 on 2026-07-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0005_remove_licensesource_notes_licensesource_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenserequest",
            name="status_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="licenserequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SIGNATURE", "Waiting Signature"),
                    ("CONTRACT", "Contract"),
                    ("FINANCE", "Finance"),
                    ("ISSUED", "Issued"),
                    ("COMPLETED", "Completed"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
