# Generated by Django 6.0.6 on 2026-07-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0005_alter_licenseattachment_attachment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenseattachment",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("LETTER", "Letter"),
                    ("COMMITMENT", "Commitment"),
                    ("PERMIT", "Permit"),
                    ("INQUIRY", "DSRS Inquiry"),
                    ("CONTRACT", "Contract"),
                    ("SPECIFICATION", "Generated Specification"),
                    ("SPECIFICATION_APPENDIX", "Specification Appendix"),
                    ("LICENSE", "Issued License letter"),
                    ("OTHER", "Other"),
                ],
                max_length=25,
                verbose_name="Attachment Type",
            ),
        ),
    ]
