# Generated by Django 6.0.6 on 2026-07-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0006_licenserequest_status_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="licensesource",
            name="description",
        ),
        migrations.AddField(
            model_name="licenserequest",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="licenseattachment",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("LETTER", "Letter"),
                    ("COMMITMENT", "Commitment"),
                    ("PERMIT", "Permit"),
                    ("INQUIRY", "DSRS Inquiry"),
                    ("CONTRACT", "Contract"),
                    ("SPECIFICATION", "Generated Specification"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
                verbose_name="Attachment Type",
            ),
        ),
    ]
