# Generated by Django 6.0.6 on 2026-08-05 10:30

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_alter_dsrs_options_alter_hideshowfiltert_options_and_more"),
        ("facilities", "0002_alter_facilitymodel_created_at_and_more"),
        ("operations", "0006_alter_licenseattachment_attachment_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="licenseapproval",
            options={
                "ordering": ["order"],
                "verbose_name": "License Approval",
                "verbose_name_plural": "License Approvals",
            },
        ),
        migrations.AlterModelOptions(
            name="licenserequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "License Request",
                "verbose_name_plural": "License Requests",
            },
        ),
        migrations.AlterModelOptions(
            name="licensesourcecomponent",
            options={
                "ordering": ["id"],
                "verbose_name": "Source Component",
                "verbose_name_plural": "Source Components",
            },
        ),
        migrations.AlterModelOptions(
            name="usersignature",
            options={
                "verbose_name": "User Signature",
                "verbose_name_plural": "User Signatures",
            },
        ),
        migrations.AlterField(
            model_name="licenseapproval",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approved At"
            ),
        ),
        migrations.AlterField(
            model_name="licenseapproval",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approver",
            ),
        ),
        migrations.AlterField(
            model_name="licenseapproval",
            name="comments",
            field=models.TextField(blank=True, verbose_name="Comments"),
        ),
        migrations.AlterField(
            model_name="licenseapproval",
            name="license",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to="operations.licenserequest",
                verbose_name="License",
            ),
        ),
        migrations.AlterField(
            model_name="licenseapproval",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="licenseapproval",
            name="step",
            field=models.CharField(
                choices=[
                    ("CREATOR", "Creator"),
                    ("MANAGER", "Manager"),
                    ("DEPUTY", "Deputy Manager"),
                    ("CONTRACTS", "Contracts"),
                ],
                max_length=30,
                verbose_name="Approval Step",
            ),
        ),
        migrations.AlterField(
            model_name="licenserequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="licenserequest",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="licenserequest",
            name="letter_date",
            field=models.DateField(blank=True, null=True, verbose_name="Letter Date"),
        ),
        migrations.AlterField(
            model_name="licenserequest",
            name="letter_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Letter Number"
            ),
        ),
        migrations.AlterField(
            model_name="licenserequest",
            name="specification_completed",
            field=models.BooleanField(
                default=False, verbose_name="Specification Completed"
            ),
        ),
        migrations.AlterField(
            model_name="licenserequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SPECIFICATION", "Preparing Specification"),
                    ("WAITING_CREATOR", "Waiting Creator Signature"),
                    ("WAITING_MANAGER", "Waiting Manager Signature"),
                    ("WAITING_DEPUTY", "Waiting Deputy Signature"),
                    ("CONTRACTS", "Contracts"),
                    ("FINANCE", "Finance"),
                    ("READY_TO_ISSUE", "Ready To Issue"),
                    ("ISSUED", "Issued"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="licenserequest",
            name="status_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Status Date"
            ),
        ),
        migrations.AlterField(
            model_name="licenserequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="licensesource",
            name="description",
            field=models.TextField(
                blank=True, max_length=50, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="licensesource",
            name="specification_order",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Specification Order"
            ),
        ),
        migrations.AlterField(
            model_name="licensesourcecomponent",
            name="quantity_used",
            field=models.PositiveIntegerField(default=1, verbose_name="Quantity Used"),
        ),
        migrations.AlterField(
            model_name="usersignature",
            name="signature",
            field=models.ImageField(upload_to="signatures/", verbose_name="Signature"),
        ),
        migrations.AlterField(
            model_name="usersignature",
            name="title",
            field=models.CharField(blank=True, max_length=150, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="usersignature",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="usersignature",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalLicenseApproval",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("CREATOR", "Creator"),
                            ("MANAGER", "Manager"),
                            ("DEPUTY", "Deputy Manager"),
                            ("CONTRACTS", "Contracts"),
                        ],
                        max_length=30,
                        verbose_name="Approval Step",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Comments")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approver",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="operations.licenserequest",
                        verbose_name="License",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical License Approval",
                "verbose_name_plural": "historical License Approvals",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLicenseRequest",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "letter_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Letter Number",
                    ),
                ),
                (
                    "letter_date",
                    models.DateField(blank=True, null=True, verbose_name="Letter Date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SPECIFICATION", "Preparing Specification"),
                            ("WAITING_CREATOR", "Waiting Creator Signature"),
                            ("WAITING_MANAGER", "Waiting Manager Signature"),
                            ("WAITING_DEPUTY", "Waiting Deputy Signature"),
                            ("CONTRACTS", "Contracts"),
                            ("FINANCE", "Finance"),
                            ("READY_TO_ISSUE", "Ready To Issue"),
                            ("ISSUED", "Issued"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "status_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Status Date"
                    ),
                ),
                (
                    "specification_completed",
                    models.BooleanField(
                        default=False, verbose_name="Specification Completed"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Updated At"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="facilities.facilitymodel",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical License Request",
                "verbose_name_plural": "historical License Requests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLicenseSourceComponent",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "quantity_used",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Quantity Used"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "dsrs",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dashboard.dsrs",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "license_source",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="operations.licensesource",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Source Component",
                "verbose_name_plural": "historical Source Components",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
