# Generated by Django 6.0.6 on 2026-09-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_alter_licenseapproval_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallicenserequest',
            name='discount_notes',
            field=models.TextField(blank=True, help_text='Written by the creator when requesting; the CEO can edit/add to it at sign time.', null=True, verbose_name='Discount Notes'),
        ),
        migrations.AddField(
            model_name='historicallicenserequest',
            name='discount_requested',
            field=models.BooleanField(default=False, help_text='If checked, the request routes to the CEO for signature after the Deputy, before Contracts.', verbose_name='Discount Requested'),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='discount_notes',
            field=models.TextField(blank=True, help_text='Written by the creator when requesting; the CEO can edit/add to it at sign time.', null=True, verbose_name='Discount Notes'),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='discount_requested',
            field=models.BooleanField(default=False, help_text='If checked, the request routes to the CEO for signature after the Deputy, before Contracts.', verbose_name='Discount Requested'),
        ),
    ]
