# Generated by Django 6.0.6 on 2026-07-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0008_alter_licenserequest_status_licenseapproval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="licensesource",
            name="description",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
