# Generated by Django 6.0.6 on 2026-09-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_historicallicenserequest_discount_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallicenseapproval',
            name='step',
            field=models.CharField(choices=[('CREATOR', 'Creator'), ('MANAGER', 'Manager'), ('DEPUTY', 'Deputy Manager'), ('CONTRACTS', 'Contracts'), ('CEO', 'CEO')], max_length=30, verbose_name='Approval Step'),
        ),
        migrations.AlterField(
            model_name='historicallicenserequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SPECIFICATION', 'Preparing Specification'), ('WAITING_CREATOR', 'Waiting Creator Signature'), ('WAITING_MANAGER', 'Waiting Manager Signature'), ('WAITING_DEPUTY', 'Waiting Deputy Signature'), ('WAITING_CEO', 'Waiting CEO Signature (Discount Requested)'), ('CONTRACTS', 'Contracts'), ('FINANCE', 'Finance'), ('READY_TO_ISSUE', 'Ready To Issue'), ('ISSUED', 'Issued'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='licenseapproval',
            name='step',
            field=models.CharField(choices=[('CREATOR', 'Creator'), ('MANAGER', 'Manager'), ('DEPUTY', 'Deputy Manager'), ('CONTRACTS', 'Contracts'), ('CEO', 'CEO')], max_length=30, verbose_name='Approval Step'),
        ),
        migrations.AlterField(
            model_name='licenserequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SPECIFICATION', 'Preparing Specification'), ('WAITING_CREATOR', 'Waiting Creator Signature'), ('WAITING_MANAGER', 'Waiting Manager Signature'), ('WAITING_DEPUTY', 'Waiting Deputy Signature'), ('WAITING_CEO', 'Waiting CEO Signature (Discount Requested)'), ('CONTRACTS', 'Contracts'), ('FINANCE', 'Finance'), ('READY_TO_ISSUE', 'Ready To Issue'), ('ISSUED', 'Issued'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
    ]
