# Generated by Django 6.0.6 on 2026-07-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0009_licensesource_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="licenserequest",
            name="contract_cost",
        ),
        migrations.RemoveField(
            model_name="licenserequest",
            name="contract_date",
        ),
        migrations.RemoveField(
            model_name="licenserequest",
            name="contract_number",
        ),
        migrations.AlterField(
            model_name="licensesource",
            name="activity_unit",
            field=models.CharField(
                choices=[
                    ("Bq", "Becquerel"),
                    ("KBq", "Kilobecquerel"),
                    ("MBq", "Megabecquerel"),
                    ("GBq", "Gigabecquerel"),
                    ("Ci", "Curie"),
                    ("mCi", "Millicurie"),
                    ("uCi", "Microcurie"),
                    ("nCi", "Nanocurie"),
                ],
                default="mCi",
                max_length=20,
                verbose_name="Activity Unit",
            ),
        ),
    ]
