# Generated by Django 6.0.6 on 2026-07-25 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0021_dsrs_available_count_dsrs_contract_dsrs_created_from_and_more",
        ),
        ("operations", "0010_remove_licenserequest_contract_cost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="licensesource",
            name="created_dsrs",
        ),
        migrations.AddField(
            model_name="licensesource",
            name="result_dsrs",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_by_licenses",
                to="dashboard.dsrs",
            ),
        ),
        migrations.AddField(
            model_name="licensesource",
            name="source_dsrs",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requested_in_licenses",
                to="dashboard.dsrs",
            ),
        ),
        migrations.AddField(
            model_name="licensesource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("NEW", "New Source"),
                    ("REUSED", "Reused Source"),
                    ("RECYCLED", "Recycled Source"),
                ],
                default="NEW",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="licensesource",
            name="activity_unit",
            field=models.CharField(
                choices=[
                    ("Bq", "Bq"),
                    ("KBq", "KBq"),
                    ("MBq", "MBq"),
                    ("GBq", "GBq"),
                    ("Ci", "Ci"),
                    ("mCi", "mCi"),
                    ("uCi", "uCi"),
                    ("nCi", "nCi"),
                ],
                default="mCi",
                max_length=20,
                verbose_name="Activity Unit",
            ),
        ),
    ]
